### PR TITLE
Fix build warnings

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @natemcmaster

**Comment by natemcmaster** [comment]
I assume this means dotnet-pack now preserves folder structure?

**Comment by pranavkm** [comment]
Yup, it's been doing that for a while now. Here's the dirtree after this change:

```
¦   Microsoft.EntityFrameworkCore.Tools.nuspec
¦   [Content_Types].xml
¦
+---lib
¦   +---net451
¦   ¦       Microsoft.EntityFrameworkCore.Tools.dll
¦   ¦       Microsoft.EntityFrameworkCore.Tools.xml
¦   ¦
¦   +---netcore50
¦   ¦       _._
¦   ¦
¦   +---netcoreapp1.0
¦           dotnet-ef.dll
¦           dotnet-ef.runtimeconfig.json
¦           dotnet-ef.xml
¦
+---tools
¦       about_EntityFrameworkCore.help.txt
¦       EntityFrameworkCore.PowerShell2.psd1
¦       EntityFrameworkCore.PowerShell2.psm1
¦       EntityFrameworkCore.psd1
¦       EntityFrameworkCore.psm1
¦       init.ps1
¦       install.ps1
¦       OperationHandlers.cs
¦
+---_rels
        .rels
```

**Comment by natemcmaster** [comment]
:shipit:

**Pull request merged**
