### PR TITLE
Throw better exception when database back propagates null for non-nullable property

### PR DESCRIPTION
**Pull request by ajcvickers**
Issue #4347

### CODE REVIEW

**Comment by lajones** [comment]
:shipit:

**Comment by ajcvickers** [comment]
Merged

**Comment by wgutierrezr** [comment]
Hi
I have this problem whit a table with a Bit field with default '0' (false). When I try to create a new record using ASP.Net Core 1.1 MVC, and EntityFrameworkCore.Sqlserver 1.1.2, passing the value for the boolean field with 'False' then it triggers this error.

Do you have any solution for this problem?

**Comment by ajcvickers** [comment]
@wgutierrezr The fix for this issue was merged some time ago. Can you please file a new issue with full details of how to reproduce what you are seeing?

**Pull request closed without merging**
