### PR TITLE
Query: Convert Order By constant & @@rowcount to (SELECT 1)

### LINKED ISSUE #6145: Query: OrderBy constant generates incorrect query for integer/boolean
At present in query,
`OrderBy(c => true)` translates to `ORDER BY 1`
`OrderBy(c => 3)` translates to  `ORDER BY 3`
In SqlServer, `ORDER BY` integer means order by that column number from projection which introduces unintended ordering and gives different results compared to what linq gives.
We are also using creating Order by when we do group join with default if empty using the left side of join condition which also faces above issue based on the join condition.
See tests `QuerySqlServerTest.OrderBy_true`, `QuerySqlServerTest.OrderBy_integer` & `GearsOfWarQuerySqlServerTest.Left_join_predicate_value_equals_condition`
Possible work-arounds:
We can remove the order by clause if it is using constant. Results would match this way with linq but for paging cases, order by clause is necessary.
We can introduce dummy order by as follows:
`Order by @@ROWCOUNT`
`Order by @parameter + 1` where @parameter is passed. Value doesn't matter.
@divega

### PR DESCRIPTION
**Pull request by smitpatel**
Fixes #6145 , #6580 
Converted OrderBy with Constant/Parameter to `(SELECT 1)`
Converted dummy `@@rowcount` to `(SELECT 1)`

### CODE REVIEW

**Comment by maumar** [comment]
:shipit:

**Comment by ErikEJ** [comment]
Now you broke the SQL CE provider...

**Comment by smitpatel** [comment]
@ErikEJ - From what I understand SQL CE was already facing issue #6145. With these changes it will throw exception instead of incorrect results.
Is there any solution in SQL CE for #6145?

**Comment by divega** [comment]
Adding [providers-beware] after the fact.

**Comment by ErikEJ** [comment]
@smitpatel No, no solution for SQLCE, currently is use GETDATE()

**Comment by smitpatel** [comment]
@ErikEJ - After discussing with @divega , we found some failing tests for CE reported in past but all of those issues are closed. Can you file a new issue for all the tests which are failing for SQL CE so we can take this discussion there and resolve what we can.

**Comment by ErikEJ** [comment]
@smitpatel  I assume you mean a consolidated list of failing test in the SQL CE provider caused by use of nested SELECT statements generated by EF.Relational ?

**Comment by smitpatel** [comment]
@ErikEJ - Yes. Cause can be anything and not just nested `SELECT` (like this one scalar subquery)

**Comment by ErikEJ** [comment]
Will do, thanks - close to 100% fail due to nested SELECTs, though

**Pull request merged**
