### PR TITLE
Add tests for #3804 - Select Navigation following Skip or Take

### PR DESCRIPTION
**Pull request by mikary**
@maumar @anpete

### CODE REVIEW

**Comment by maumar** [comment]
you might want to hold of on this checkin - I just submitted a PR that adds better result verification for the navigation tests. I think we should take advantage of it for all the new tests that are being added

**Comment by divega** [comment]
@maumar @mikary should we now revisit this PR?

**Comment by mikary** [comment]
@divega I've been looking into adding tests for a number of related issues (#3804 #3674 #3676 and #3913) that have been resolved (or partially resolved in the case of #3676) and adding tests for the scenarios described in the issues to avoid regressions. All of these tests would be in `QueryNavigationsTestBase` and I'm looking at consolidating all of these tests into one PR.

**Comment by mikary** [comment]
@maumar updated with tests for the listed issues

**Comment by maumar** [comment]
:shipit:

**Pull request merged**
