### PR TITLE
Make IMigrationsModelDiffer a provider service

### PR DESCRIPTION
**Pull request by ajcvickers**
Issue #6522

Service was already scoped, so the change is minimal.

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
`MigrationsModelDiffer.Sort` should be split into two methods so that it doesn't need to be completely reimplemented when adding an operation

**Comment by ajcvickers** [comment]
@AndriySvyryd Filed #6529

**Comment by bricelam** [comment]
Should `MigrationsModelDiffer` move out of `.Internal`?

**Comment by ajcvickers** [comment]
@bricelam Possibly, if we are recommending that it be extended for this scenario. Currently the service is public, but our implementation is internal, which is normal for services that we expect people to replace. But if we expect the service to be replaced by extending the existing implementation, then it probably should be public.

**Comment by ajcvickers** [comment]
It's probably worth saying that the point of this PR is to allow the PostgreSQL provider to do what it is currently doing in a way that is friendly in multiple provider scenarios. While we can choose to do more to support doing this, for example, without using internal code, it is valid for a provider to use internal code as long as it is understood that the provider may be broken when there is an EF update. So I think we should get this change in as a minimum step, and then choose to do more or not as appropriate.

**Comment by rowanmiller** [comment]
Agreed with not needing to move the implementation out of internal at this stage

**Comment by bricelam** [comment]
Given our [design meeting discussion](https://github.com/aspnet/EntityFramework/wiki/Design-Meeting-Notes-(September-15,-2016)) on this, I think we can close it now.

**Pull request closed without merging**
