### PR TITLE
Running more tests using dotnet test

### PR DESCRIPTION
**Pull request by pranavkm**
cc @natemcmaster

### CODE REVIEW

**Comment by natemcmaster** [comment]
@pranavkm thanks for this! Work is partially underway in #4638 to completely switch to dotnet-test. Mind if I merge your commit into that so we can get one big change at the same time?

**Comment by pranavkm** [comment]
That makes sense. Feel free to close this PR out if you're merging in the changes.

**Comment by natemcmaster** [comment]
Ok. I'll merge this with my ongoing work to fixup tests.

**Comment by natemcmaster** [comment]
Added the changes to #4638

**Pull request closed without merging**
