### PR TITLE
Cache services in some places to avoid multiple calls to GetService.

### PR DESCRIPTION
**Pull request by ajcvickers**

### CODE REVIEW

**Comment by anpete** [comment]
:shipit:

**Comment by divega** [comment]
@ajcvickers @anpete is this for "1.0.1"?

**Comment by ajcvickers** [comment]
@divega Depends on the bar for 1.0.1 per our discussion at lunch. If we decide to only take high priority fixes in patch releases, then I don't think this makes the cut. If we decide to take any non-feature change, then yes it would go in 1.0.1.

**Comment by divega** [comment]
Thanks. The main purpose of my question was to make sure there were not things we wanted to take for 1.0.0. We can figure out where they go after (we have only defined a milestone for 1.0.1 but they might not belong there). It is good information that these would require breaking changes to internal surface.

**Comment by ajcvickers** [comment]
@divega This one doesn't break internal APIs. The other one does.

**Pull request merged**
