### PR TITLE
Making tracking more pay-per-play in query

### PR DESCRIPTION
**Pull request by ajcvickers**
Lazily resolve services related to tracking from query such that they will not be loaded when only no-tracking queries are used.

### CODE REVIEW

**Comment by anpete** [comment]
@ajcvickers Can we add a regression test? (reflection?)

**Comment by divega** [comment]
@ajcvickers @anpete is this something we are planning to take in "1.0.1"?

**Comment by ajcvickers** [comment]
@divega Probably have to wait for the first point release, per discussion on internal APIs at lunch.

**Comment by ajcvickers** [comment]
@anpete Updated with test,

**Comment by anpete** [comment]
:shipit:

**Pull request merged**
