### PR TITLE
Include()/ThenInclude() internal rework to have navigations be a tree instead of flat list

### LINKED ISSUE #4490: Request for "AlsoInclude"  (peer level)
I like the Include().ThenInclude() syntax of EF7.   It would also be great if there was an "AlsoInclude" so that when you want to include another peer several levels deep, you don't have to start at the top (with Include) again.  You start getting these really long statements with many include, then include, then include  (back to) include, then include, then include, then include,  etc.  Not a big deal or nothing.  It works as is, but syntactically could certainly be more readable if we had a peer level include  (ie, whatever entity the last include or ThenInclude was referencing).

### LINKED ISSUE #4900: Repeated joins on repeated .Include().ThenInclude()
Working with RC1

Assuming the sample schema:
DB contains Forums
Forum has many Users
Forum has many Posts
Post has many Comments

The code:
```
				var res3 = db.Users
					.Include(u => u.Forum)
					.Include(u => u.Forum)
					.ToList();
```

Generates the query:

```
SELECT [u].[UserId], [u].[ForumId], [u].[Name], [f].[ForumId], [f].[Name], [f0].[ForumId], [f0].[Name]
FROM [User] AS [u]
INNER JOIN [Forum] AS [f] ON [u].[ForumId] = [f].[ForumId]
INNER JOIN [Forum] AS [f0] ON [u].[ForumId] = [f0].[ForumId] <====
```

While this sample may seem fake, it is less so in this case, using .ThenInclude():
```
				var res5 = db.Users.Where(u => u.Name == "user1")
					.Include(u => u.Forum).ThenInclude(f => f.Posts)
					.Include(u => u.Forum).ThenInclude(f => f.Users)
					.ToList();
```

Which generates:
```
SELECT [u].[UserId], [u].[ForumId], [u].[Name], [f].[ForumId], [f].[Name], [f0].[ForumId], [f0].[Name]
FROM [User] AS [u]
INNER JOIN [Forum] AS [f] ON [u].[ForumId] = [f].[ForumId]
INNER JOIN [Forum] AS [f0] ON [u].[ForumId] = [f0].[ForumId] <====
WHERE [u].[Name] = 'user1'
ORDER BY [f].[ForumId], [f0].[ForumId]
```
And also:
```
SELECT [u].[UserId], [u].[ForumId], [u].[Name]
FROM [User] AS [u]
INNER JOIN (
    SELECT DISTINCT [f].[ForumId], [f0].[ForumId] AS [ForumId0]
    FROM [User] AS [u]
    INNER JOIN [Forum] AS [f] ON [u].[ForumId] = [f].[ForumId]
    INNER JOIN [Forum] AS [f0] ON [u].[ForumId] = [f0].[ForumId] <====
    WHERE [u].[Name] = 'user1'
) AS [f0] ON [u].[ForumId] = [f0].[ForumId0]
ORDER BY [f0].[ForumId], [f0].[ForumId0]
```
And then:
```
SELECT [p].[PostId], [p].[ForumId], [p].[Title]
FROM [Post] AS [p]
INNER JOIN (
    SELECT DISTINCT [f].[ForumId]
    FROM [User] AS [u]
    INNER JOIN [Forum] AS [f] ON [u].[ForumId] = [f].[ForumId]
    WHERE [u].[Name] = 'user1'
) AS [f] ON [p].[ForumId] = [f].[ForumId]
ORDER BY [f].[ForumId]
```

Is this a bug or am I doing something wrong?

### PR DESCRIPTION
**Pull request by multiarc**
Initial pull request: https://github.com/aspnet/EntityFramework/pull/5957
```
Summary of the changes
-  Include duplicates in query fix, reworked include specifications to be tree like structure of navigations, a lot of associated changes done to make it work.
-  Includes API remains unchanged.
-  A lof of SQL Gen Tests containing multiple Includes should fail after this change, so they all should be reworked.

Fixes #4900
Closes #4490 as no API change needed to resolve duplicates internally
```

**Please check if the PR fulfills these requirements**
- [ ] The code builds and tests pass (verified by our automated build checks)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Code meets the expectations our engineering guidelines. https://github.com/aspnet/Home/wiki/Engineering-guidelines.

### CODE REVIEW

**Comment by multiarc** [comment]
@rowanmiller @anpete With latest code base no issues initially happening. Seems like I need some help understanding what CheckIsLoaded() is doing specifically for InMemory tests. Because all InMemory Include tests failed.

**Comment by anpete** [comment]
@multiarc We are reworking how Includes get compiled at the moment, basically attempting to leverage our support for nav. rewrite instead of having separate Include code paths in each provider. 79610a335598a contains the first part of the changes. I'm hoping to get rid of a lot of code after this is done :smile:

**Comment by multiarc** [comment]
@anpete I would like to see working rewriting, this would be nice to have optimized trees compilation. 

Initially I was trying to rewrite them too, and I expirenced a lot of issues so I just making a trick and building include tree earlier, so EF working with initial includes in Expression as is and differently on querying and compilation.
``` csharp
private static IEnumerable<IncludeSpecification> CreateSpecifications(IEnumerable<IncludeSet> includeSets)
{
    return includeSets.GroupBy(i => new IncludeKey
    {
        QuerySource = i.QuerySource,
        Navigation = i.Navigations[0]
     }, IncludeKey.QuerySourceNavigationComparer)
        .Select(
            i =>
                new IncludeSpecification(i.Key.QuerySource, i.Key.Navigation,
                    CreateSpecifications(
                        i.Where(l => l.Navigations.Length > 1)
                            .Select(l => new IncludeSet
                            {
                                QuerySource = l.QuerySource,
                                Navigations = l.Navigations.Skip(1).ToArray()
                            })
                        ).ToList()
                    )
        );
}
```
Also we already using our fork in production for almost 6 months, not without issues, because it's not merged all together with latest fixes and pretty hard to do merges every release. So either way mine solution (this requires some optimizations especially with this GroupBy trick) but overall looks stable and no issues for the back referenced entities because technically there is no duplicated materialization and fixup completes single time for every entity.

**Comment by multiarc** [comment]
@anpete I resolved issues I had.
Looking on sql gen tests failing right now, they obviously broken with the changes I made. 
Want me to fix tests (as functionality isn't broken)?

**Comment by ajcvickers** [comment]
@multiarc We have discussed this again and based on the re-work of includes we don't think that these changes align with our current architecture. It is hard coordinating multiple people working in the same area, and sometimes it happens that various changes take the code in different directions. We appreciate your desire to contribute and we apologize for not being able to take this change.

**Pull request closed without merging**
