### PR TITLE
Version Core and Relational functional tests

### LINKED ISSUE #2252: Versioning of EF Test MyGet packages
Great that those test packages are now available for easy comsumprion in for example providers. But there seems to be a issue with the versioning, as both packages have version 1.0.0.  It would be useful if they had the same version number as the "daily" build.

     EntityFramework.Core.FunctionalTests  v1.0.0

### PR DESCRIPTION
**Pull request by bricelam**
Fixes #2252

### CODE REVIEW

**Comment by lajones** [comment]
:shipit: Looks good. By why only these test projects?

**Comment by bricelam** [comment]
@lajones They're the only ones we "ship".

**Comment by lajones** [comment]
Sure - they're the only ones needed right now - but wouldn't it be more consistent to have them all the same?

**Comment by bricelam** [comment]
Tests don't need versions. I'm really just adding a version to the nupkgs. The other ones don't ever produce nupkgs--they're ran from source.

**Comment by bricelam** [comment]
Eventually we'll even remove these ones once we have a long-term solution for testing providers.

**Comment by lajones** [comment]
OK. Not a big issue.

**Pull request merged**
