### PR TITLE
Add NETStandard.Library.NETFramework for older versions of Visual Studio

### PR DESCRIPTION
**Pull request by smitpatel**
@bricelam @ajcvickers

### CODE REVIEW

**Comment by bricelam** [comment]
@ryanbrandenburg any harm in keeping this a while longer?

**Comment by ryanbrandenburg** [comment]
The problem is `NETStandard.Library.NETFramework` will stop shipping at some point, so there will be a stale version on the feed until we clean it, at which point this will start to fail.

**Comment by smitpatel** [comment]
I think it is ok. We can remove this once it start to fail.

**Comment by smitpatel** [comment]
> there will be a stale version on the feed until we clean it, at which point this will start to fail.

It is available on NuGet feed so restore will never fail even if we clean our feeds. If the stale version causes errors then we can remove it.

**Comment by ryanbrandenburg** [comment]
What about the time before it fails when that package is stale?

**Comment by smitpatel** [comment]
> What about the time before it fails when that package is stale?

We can always remove it if it fails. Nothing stops us from doing so in future. No need to deteriorate dev experience for that.

**Comment by ErikEJ** [comment]
What issue does this solve??

**Comment by bricelam** [comment]
@ErikEJ It makes developing EF Core slightly easier with VS 15.2

**Pull request merged**
