### PR TITLE
Remove Microbenchmarks projects

### PR DESCRIPTION
**Pull request by natemcmaster**
cc @bricelam @rowanmiller

Iincidentally, also fixed up running tests from csproj.

### CODE REVIEW

**Comment by bricelam** [comment]
(un-):shipit:

**Comment by roji** [comment]
Can you guys say where this went? Did you move it to a separate repo (where) or throw it out entirely? Am interested in looking at how you're doing benchmarking.

**Comment by bricelam** [comment]
Moved to a private repo. @rowanmiller are there any plans to make it public?

**Comment by bricelam** [comment]
Also, the links on [perf.efproject.net](http://perf.efproject.net) need updating.

**Comment by natemcmaster** [comment]
Rowan is out on leave for 6 weeks, so probably nothing will happen soon. But AFAIK we plan to open source the benchmarks repo. 

@roji checkout the code at https://github.com/aspnet/EntityFramework/tree/00bb8e13df3328511d3eca70d1fb6a3518329176 (the parent of this PR) to see how we are doing some microbenchmarks.

**Comment by roji** [comment]
@natemcmaster ok thanks, will do. Have already started working with BenchmarksDotNet and am having a great time.

**Pull request merged**
