### PR TITLE
Transition to Netstandard.

### PR DESCRIPTION
**Pull request by NTaylorMullen**
- dotnet5.X => netstandard1.y (where y = x-1).
- DNXCore50 => netstandardapp1.5.
- Applied the same changes to ifdefs.

### CODE REVIEW

**Comment by smitpatel** [comment]
@natemcmaster @bricelam @divega @rowanmiller

**Comment by NTaylorMullen** [comment]
Thanks @smitpatel

**Comment by natemcmaster** [comment]
Heads up, you might need to do a big rebase. We are just finishing up big changes for dotnet-test. See #4638

**Comment by NTaylorMullen** [comment]
I'll just re-run my tool once your bits are in. If you guys could just look over these changes to make sure nothing is completely messed up that'd be good.

**Comment by natemcmaster** [comment]
Looks fine.

**Comment by natemcmaster** [comment]
@NTaylorMullen we merged that other PR. Looks like this has merge conflicts now.

**Comment by NTaylorMullen** [comment]
This is in.

**Pull request closed without merging**
