### PR TITLE
Make AddMyProvider methods act like top-level service methods

### PR DESCRIPTION
**Pull request by ajcvickers**
Since these now hang directly off IServiceCollection they should behave in the same way as other methods that are here. Specifically:
- Renamed to indicate that they are methods for adding EntityFramework with a specific provider
- Add their dependencies automatically--that is, call AddEntityFramework

This means that AddEntityFramework is now a infrastructure method, like AddRelational, that is called by providers. It has therefore been moved to the Infrastructure namespace.

### CODE REVIEW

**Comment by ajcvickers** [comment]
Could somebody take a quick look at this? It's a very straightforward change and once it is reviewed I can start merging the D.I. changes.

**Comment by anpete** [comment]
:shipit:

**Comment by anpete** [comment]
Might be nice to have nested closure here, too

**Comment by ajcvickers** [comment]
Merged

**Pull request closed without merging**
