### PR TITLE
fix join IGrouping with IAsyncEnumerable

### LINKED ISSUE #8938: Asynchronous mode does not work
Synchronous mode works, Asynchronous mode does not work

```
Exception message:
Expression of type 'System.Collections.Generic.IEnumerable`1[System.Tuple`1[System.String]]' cannot be used for return type 'System.Collections.Generic.IAsyncEnumerable`1[System.Tuple`1[System.String]]'

Stack trace:
   at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters, String paramName)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, ParameterExpression[] parameters)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateExecutorLambda[TResults]()
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at EfCoreBug.Program.CreateAsyncQueryExecutor[T](DbContext dbContext, Expression expression) in D:\vorona\EfCoreBug\EfCoreBug\Program.cs:line 70
   at EfCoreBug.Program.Main(String[] args) in D:\vorona\EfCoreBug\EfCoreBug\Program.cs:line 59
```

### Steps to reproduce
```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Query;
using Remotion.Linq;
using Remotion.Linq.Parsing.ExpressionVisitors.Transformation;
using Remotion.Linq.Parsing.ExpressionVisitors.TreeEvaluation;
using Remotion.Linq.Parsing.Structure;
using Remotion.Linq.Parsing.Structure.ExpressionTreeProcessors;
using Remotion.Linq.Parsing.Structure.NodeTypeProviders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;

namespace EfCoreBug
{
    public sealed class Order
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public sealed class OrderItem
    {
        public int Id { get; set; }
        public Order Order { get; set; }
        public int OrderId { get; set; }
    }

    public sealed class OrderContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseInMemoryDatabase("test");
            base.OnConfiguring(optionsBuilder);
        }

        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderItem> OrderItems { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var dbContext = new OrderContext())
            {
                dbContext.Orders.Add(new Order() { Id = 1, Name = "order 1" });
                dbContext.OrderItems.Add(new OrderItem() { Id = 1, OrderId = 1 });
                dbContext.SaveChanges();

                var queryContextFactory = dbContext.GetService<IQueryContextFactory>();
                QueryContext queryContext = queryContextFactory.Create();
                IQueryable<Tuple<string>> query = dbContext.OrderItems.GroupBy(i => i.Order.Id).Select(g => new Tuple<string>(g.Max(i => i.Order.Name)));

                Func<QueryContext, IEnumerable<Tuple<string>>> executorSync = CreateQueryExecutor<Tuple<string>>(dbContext, query.Expression);
                List<Tuple<string>> resultSync = executorSync(queryContext).ToList();

                Func<QueryContext, IAsyncEnumerable<Tuple<string>>> executorAsync = CreateAsyncQueryExecutor<Tuple<string>>(dbContext, query.Expression);
                List<Tuple<string>> resultAsync = executorAsync(queryContext).ToList().GetAwaiter().GetResult();
            }
        }

        private sealed class ApiCompilationFilter : EvaluatableExpressionFilterBase { }

        public static Func<QueryContext, IAsyncEnumerable<T>> CreateAsyncQueryExecutor<T>(DbContext dbContext, Expression expression)
        {
            QueryModel queryModel = CreateQueryModel(dbContext, expression);
            var queryCompilationContextFactory = dbContext.GetService<IQueryCompilationContextFactory>();
            return queryCompilationContextFactory.Create(true).CreateQueryModelVisitor().CreateAsyncQueryExecutor<T>(queryModel);
        }
        public static Func<QueryContext, IEnumerable<T>> CreateQueryExecutor<T>(DbContext dbContext, Expression expression)
        {
            QueryModel queryModel = CreateQueryModel(dbContext, expression);
            var queryCompilationContextFactory = dbContext.GetService<IQueryCompilationContextFactory>();
            return queryCompilationContextFactory.Create(false).CreateQueryModelVisitor().CreateQueryExecutor<T>(queryModel);
        }
        private static QueryModel CreateQueryModel(DbContext dbContext, Expression expression)
        {
            INodeTypeProvider nodeTypeProvider = dbContext.GetService<MethodInfoBasedNodeTypeRegistry>();
            var queryParser = new QueryParser(
                new ExpressionTreeParser(nodeTypeProvider,
                new CompoundExpressionTreeProcessor(
                    new IExpressionTreeProcessor[]
                    {
                            new PartialEvaluatingExpressionTreeProcessor(new ApiCompilationFilter()),
                            new TransformingExpressionTreeProcessor(ExpressionTransformerRegistry.CreateDefault())
                    })));
            return queryParser.GetParsedQuery(expression);
        }
    }
}
```

### Further technical details
EF Core version: 1.1.2
Database Provider: SqlServer 1.1.2, InMemory 1.1.2
Operating system: Windows 7, Windows 10
IDE: Visual Studio 2017

### PR DESCRIPTION
**Pull request by voronov-maxim**
resolve #8938

### CODE REVIEW

**Comment by anpete** [comment]
Hi @voronov-maxim, thanks for the PR! Can you please add a regression test to QueryTestBase?

**Comment by voronov-maxim** [comment]
Hi @anpete, what should be right:
1. I create a new PR with test
or
2. I close this PR and create a new one with fixed bug & test

**Comment by anpete** [comment]
Use the same PR, just add a new commit to your branch and push and the PR will be updated.

**Comment by voronov-maxim** [comment]
I can't write test on QueryTestBase
[InMemoryDatabase provider has switching into sync mode](https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore.InMemory/Storage/Internal/InMemoryDatabase.cs#L85)
and uses LinqOperatorProvider instead AsyncLinqOperatorProvider
so I couldn't retry a bug.

But I can write test to SqlServer provider, for example:
```c#
using (var context = CreateContext())
{
           var results = await context.Orders.GroupBy(c => c.EmployeeID).Select(g => new { max = g.Max(i => i.Customer.Region) }).ToListAsync();
 }
```

**Comment by anpete** [comment]
@voronov-maxim That's fine.

**Pull request merged**
