### PR TITLE
Add ToObservableCollection to LocalView so that it can be used for data binding

### PR DESCRIPTION
**Pull request by ajcvickers**
Issue #7397

In EF Core, DbSet.Local is a pure view over the state manager. This is much more efficient for normal local queries, etc., but doesn't work for data binding because it does not preserve order or maintain indexes. This change adds DbSet.Local.ToObservableCollection() which creates a less efficient but maintains order and indexes.

### CODE REVIEW

**Comment by divega** [comment]
I wondering if we should consider implementing `IListSource` and `BindingList<T>`. Probably none of this is urgent.

**Comment by ajcvickers** [comment]
@divega Do you mean implementing on some other class in addition to what we already have?

**Comment by ajcvickers** [comment]
Since this is a minor breaking change I would love to get it into preview2. @divega Did you review this? Could someone else look at it? @smitpatel @bricelam @AndriySvyryd @anpete

**Comment by divega** [comment]
@ajcvickers I meant `IListSource` on `.Local` and binding list in a different class. I can create a new issue to review how what we have works with different flavors of data binding.

**Comment by ajcvickers** [comment]
Sure, we should review what we have.

**Pull request merged**
