### PR TITLE
Add missing assembly descriptions to tooling libraries

### PR DESCRIPTION
**Pull request by natemcmaster**
Unblocks ASP.NET CI

cc @ajaybhargavb @pranavkm

### CODE REVIEW

**Comment by ajaybhargavb** [comment]
:shipit:

**Comment by pranavkm** [comment]
Add it to the project.json instead. See https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.Design/project.json#L3

**Comment by natemcmaster** [comment]
We don't use project.json on these projects to pack.

**Comment by natemcmaster** [comment]
@pranavkm to clarify...does it matter if the description is in code or in project.json? AFAIK the only reason to have it in project.json is so dotnet-pack picks this up in addition to generating AssemblyDescriptionAttribute. But since we use nuspec instead, does it matter?

**Comment by pranavkm** [comment]
Fair enough. :shipit:

**Pull request merged**
