### PR TITLE
Upgrade SqlClient on CoreClr

### PR DESCRIPTION
**Pull request by natemcmaster**
Let's try this again. DNX recently took a new version of coreclr.

### CODE REVIEW

**Comment by anpete** [comment]
:shipit:

**Comment by divega** [comment]
@natemcmaster Should this also go in the release branch?

**Comment by natemcmaster** [comment]
@divega yes, we can put this in release.

**Comment by divega** [comment]
Thanks please get it approved for beta8 if you haven't already.

**Pull request merged**
