### PR TITLE
Migrations: Allow multi-statement history table create scripts

### LINKED ISSUE #3963: Changing MigrationsHistoryTableSchema generates error in migration generation
Using this extension method to set the migration table name and schema on the current `SqlServerOptionsExtension` allows to override the migration table name and schema:

``` c#
public static DbContextOptionsBuilder UseMigrationHistoryTable(this DbContextOptionsBuilder optionsBuilder, string migrationsHistoryTableName, string migrationsHistoryTableSchema = null)
{
	if (string.IsNullOrWhiteSpace(migrationsHistoryTableName))
	{
		return optionsBuilder;
	}

	var orCreateExtension = GetOrCreateExtension(optionsBuilder);
	orCreateExtension.MigrationsHistoryTableName = migrationsHistoryTableName;

	if (!string.IsNullOrWhiteSpace(migrationsHistoryTableSchema))
	{
		orCreateExtension.MigrationsHistoryTableSchema = migrationsHistoryTableSchema;
	}

	((IDbContextOptionsBuilderInfrastructure)optionsBuilder).AddOrUpdateExtension(orCreateExtension);

	return optionsBuilder;
}

private static SqlServerOptionsExtension GetOrCreateExtension(DbContextOptionsBuilder optionsBuilder)
{
	var extension = optionsBuilder.Options.FindExtension<SqlServerOptionsExtension>();
	return extension == null ? new SqlServerOptionsExtension() : new SqlServerOptionsExtension(extension);
}
```

If only the table name is provided the migrations can be executed correctly and the migration table name gets effectively changed. However, when also the schema is provided the following exception is thrown:
```
GetCreateScript only handles operations in a single batch. For more advanced scenarios, override HistoryRepository.GetCreateScript in your provider.

   at Microsoft.Data.Entity.Migrations.HistoryRepository.GetCreateScript()
   at Microsoft.Data.Entity.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.Data.Entity.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
```

### PR DESCRIPTION
**Pull request by bricelam**
Fixes #3963

### CODE REVIEW

**Comment by ajcvickers** [comment]
:shipit:

**Comment by ErikEJ** [comment]
And this will still work with SQL CE?

**Comment by bricelam** [comment]
@ErikEJ Yes, the only real case is for schemes which I assume are ignored there.

**Comment by bricelam** [comment]
Note, this is just about the history table

**Comment by ErikEJ** [comment]
Thanks. Yes, schemas are not a SQL CE concept  - too small for that :-)

**Pull request merged**
