### PR TITLE
Remove hard-coding of UseSqlServer() in non-provider-specific templates

### PR DESCRIPTION
**Pull request by lajones**
@ErikEJ @natemcmaster 
Fix for part of issue #2465 - remove hard-coding of UseSqlServer() in non-provider-specific templates.

### CODE REVIEW

**Comment by ErikEJ** [comment]
LGTM!

**Comment by natemcmaster** [comment]
We need to also add the OnConfiguringConfigurations for SQLite

**Comment by lajones** [comment]
@natemcmaster - yep - you are right. This was also addressed by the 2nd commit.

**Comment by natemcmaster** [comment]
:shipit:

**Comment by ErikEJ** [comment]
:shipit:

**Comment by lajones** [comment]
Checked in with commit c29a9a6

**Pull request closed without merging**
