### PR TITLE
Make SqlGeneratorTestBase implementation independent by removing dbo constant as table schema

### PR DESCRIPTION
**Pull request by bartdevriendt**
Inherited tests should be able to override the schemaname

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@bartdevriendt__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, MSOTBOT;

**Comment by ErikEJ** [comment]
What about relational providers that do not have "schemaname" at all?

**Comment by bartdevriendt** [comment]
You can override the VisitTableExpression to fix this.  This is my implementation for MySql:

public override Expression VisitTableExpression(TableExpression tableExpression)
        {
            Check.NotNull(tableExpression, "tableExpression");

            Sql.Append(DelimitIdentifier(tableExpression.Table))
                .Append(" AS ")
                .Append(DelimitIdentifier(tableExpression.Alias));

            return tableExpression;
        }

**Comment by rowanmiller** [comment]
@AndriySvyryd  can you process this one

**Comment by msotclas** [comment]
__@bartdevriendt__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by ajcvickers** [comment]
@AndriySvyryd or @divega Could one of you sign off on this and then I will bring it in.

**Comment by anpete** [comment]
:shipit:

**Comment by ajcvickers** [comment]
@bartdevriendt, Can you please squash your commits into one?

**Comment by bartdevriendt** [comment]
@ajcvickers I'm not sure if it's ok now ?

**Comment by ajcvickers** [comment]
@bartdevriendt We want to be able to pull in only one commit for this. Currently you have multiple commits. The usual way to do this is to take the multiple commits and "squash" them into one. This link I just Bingled may help: http://stackoverflow.com/questions/5308816/how-to-use-git-merge-squash

**Comment by bartdevriendt** [comment]
@ajcvickers I had to create a new pull request from a branch to be able to squash everything in 1 commit  -> see #1724

**Pull request closed without merging**
