### PR TITLE
fix to 1872 - add support to DateTime.UtcNow

### PR DESCRIPTION
**Pull request by maumar**

### CODE REVIEW

**Comment by maumar** [comment]
@anpete

**Comment by anpete** [comment]
:shipit:

**Comment by divega** [comment]
Is this based on #2837?

**Comment by divega** [comment]
I meant #2873 :smile:

**Comment by maumar** [comment]
Yes, but the guy is not responding (pinged him twice). I could clean up myself, but he has 2 commits, so either I squash and we loose his name from git history, or we shall have 3 commits for this tiny change. Thoughts?

Sent from my Windows Phone
________________________________

**Pull request closed without merging**
