### PR TITLE
Make AssertQuery protected

### PR DESCRIPTION
**Pull request by roji**
For provider test suites which extend QueryTestBase

### CODE REVIEW

**Comment by smitpatel** [comment]
@roji - Can you change all `AssertQuery` to `protected`. In future other providers may need other overloads.

**Comment by roji** [comment]
Done

**Comment by smitpatel** [comment]
@anpete @ajcvickers @divega - 2.0 milestone?

**Comment by divega** [comment]
Sounds good to me. @ajcvickers?

**Comment by ajcvickers** [comment]
Yes, especially since this is only test changes.

**Comment by smitpatel** [comment]
Merged with be888c3b4d16583787bf0af5d708f7f68f03f504

**Pull request closed without merging**
