### PR TITLE
[Test] Disabling parallel build to identify issue

### PR DESCRIPTION
**Pull request by smitpatel**

### CODE REVIEW

**Comment by smitpatel** [comment]
It did not work. Guess MSBuild just hangs while building projects
@ryanbrandenburg @mikeharder - Any insights or known issue?

**Comment by mikeharder** [comment]
What is the problem you are trying to solve?

**Comment by smitpatel** [comment]
Look at travis CI logs

**Comment by mikeharder** [comment]
Is the issue that EF fails on Travis?  When did this start?  Does it repro outside Travis?

**Comment by smitpatel** [comment]
It started 5 days ago. First failure in dev https://travis-ci.org/aspnet/EntityFramework/builds/231739667

In last 5 days more than 15 builds started but only 2 of them went past building the project. It terminates after package restore and before projects are built. It works fine on Ubuntu VM for me.

**Comment by mikeharder** [comment]
Might have started after we ingested the preview2 CLI.  I leave further investigation to @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Since this doesn't happen on UbuntuUniverse builds it's not just an Ubuntu problem. Have you tried recreating the build environment as per [this](https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally)?

**Comment by smitpatel** [comment]
@ryanbrandenburg - Thanks for info. I will try that out.

**Pull request closed without merging**
