### PR TITLE
Updating dependencies for 1.0.2

### PR DESCRIPTION
**Pull request by JunTaoLuo**
Thanks for fixing the test @natemcmaster. The dependencies have been updated, and the version number has been bumped up to 1.0.2. Verified to build locally. 

cc @pranavkm

### CODE REVIEW

**Comment by pranavkm** [comment]
@divega \ @bricelam didn't you guys already have a branch with 1.0.2 changes?

**Comment by divega** [comment]
@pranavkm yes, it is rel/1.0.2.

**Comment by pranavkm** [comment]
Gotcha. I guess the versions weren't updated in the branch. :shipit:  @JunTaoLuo

**Comment by divega** [comment]
Yes, that seems to be the case.

**Pull request merged**
