### PR TITLE
Added result verification helper methods for ComplexNavigations test suite

### PR DESCRIPTION
**Pull request by maumar**
Removing a lot of code duplication in the tests.

### CODE REVIEW

**Comment by maumar** [comment]
@anpete @smitpatel

**Comment by roji** [comment]
Probably providers-beware, no?

**Comment by maumar** [comment]
@roji hopefully it won't affect providers that much, the result sql is the same for all cases. The only thing that changed was the base test class.

**Comment by maumar** [comment]
merged 370239211eda58140d1dedd96896b99228d75896

**Pull request closed without merging**
