### PR TITLE
PMC Tools: Add -UseDatabaseNames to Scaffold-DbContext

### PR DESCRIPTION
**Pull request by bricelam**

### CODE REVIEW

**Comment by ajcvickers** [comment]
Discussed with @bricelam and decided these changes don't meet the bar for 2.0 at this time.

**Comment by bricelam** [comment]
(Updated to `dev`. Reverted breaking changes.)

**Comment by Serexx** [comment]
I chased the Pascal/CamelCase issue around several other issues, discovered the '--use-database-names' change on another issue and when that didn't work found my way here. Yay.

This thread sounds like the change has been abandoned, or was deferred to 2.0 and then dropped from there, but I don't spend a ton of time here and am left unclear as to final/current status.

Could we please have a concise statement of status ?

**Comment by ajcvickers** [comment]
@Serexx the option '--use-database-names' is implemented for the `dotnet ef` command and will ship with 2.0. This PR was about adding an equivalent to the Package Manager Console commands, which didn't make it for 2.0 but will be in 2.1.

**Comment by Serexx** [comment]
Thanks!

**Comment by kirodge** [comment]
-UseDatabaseNames is in the PMC-Tools documentation, which is confusing since 2.1 is in prerelease
https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell#scaffold-dbcontext

**Pull request merged**
