### PR TITLE
Fixed a bug with group join returning incorrect outer entities

### PR DESCRIPTION
**Pull request by joshcomley**
Suppose the following model:

    public class Order
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public int? Id { get; set; }
        public Customer Customer { get; set; }
    }

    public class Customer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Order> Orders { get; set; }
    }

**Note: it is crucial we have a nullable Customer entity in this relationship to trigger the group join**

Then suppose we have the following data:

- Order ID 1 - Customer ID 1
- Order ID 2 - Customer ID 1
- Order ID 3 - Customer ID 1
- Order ID 4 - Customer ID [null]

Currently your results set would look like this:

- Order ID 1 - Customer ID 1
- Order ID 1 - Customer ID 1
- Order ID 1 - Customer ID 1
- Order ID 4 - Customer ID [null]

This is (I think) because we are not checking in the group join if the outer element has changed.

I am unable to run tests on my machine, so my apologies if this is a bad pull request.

### CODE REVIEW

**Comment by joshcomley** [comment]
Ah yep I broke the build. I can't get the main build script working on my machine, so I am unsure how to run the tests locally

**Comment by natemcmaster** [comment]
@joshcomley you should be able to run `build initialize` and then open VS and run tests from there.

**Comment by joshcomley** [comment]
Ah I just saw this, yes I did that on my clone and it didn't work. I then made a fork for the tiny change, and assumed that would fail on `build initialize` too, but I just tried it and it succeeds where the clone didn't, so now I can try to get the tests to pass before pushing back to this branch.

**Comment by joshcomley** [comment]
The build and tests are now fixed for this change. I have added the ability to resolve the key object of the outer part of the left join to the Shaper class and relevant dependencies.

**Comment by anpete** [comment]
Hi @joshcomley. Thanks for the PR! Any chance you can add a corresponding query test? You should be able to add it to ComplexNavigationsQueryTestBase - I think the model used in those tests has an optional one-to-many.

**Comment by joshcomley** [comment]
@anpete Sure thing, will sort this later today or tomorrow morning! I was intending to do it but hadn't had time to research the tests to find where is the right place, so thank you for the pointer :)

**Comment by maumar** [comment]
@joshcomley would you be able to clean up the pull request  (fix formatting, remove commented code, add test, rebase, squash) - we decided to take the fix to RC2

**Comment by maumar** [comment]
The bug got fixed in e169d17243760ac3eece58bf8187905665ab67f6, closing this PR

**Pull request closed without merging**
