### PR TITLE
DNX Commands: Kabob-case all the things

### PR DESCRIPTION
**Pull request by bricelam**
@davidfowl said it's more idiomatic...

### CODE REVIEW

**Comment by divega** [comment]
I personally like it better like this but I would like to hear what others think.

**Comment by anpete** [comment]
Looks better to me.

**Comment by smitpatel** [comment]
:+1:

**Comment by lajones** [comment]
:+1:

**Comment by natemcmaster** [comment]
:+1: I think that's enough team votes to :shipit:

**Pull request merged**
