### PR TITLE
Query: Assign non-null alias to AliasExpression only inside a subquery

### LINKED ISSUE #7103: 'SUM' is not a recognized built-in function name.
**PROBLEM FOUND: NULLABLE FIELD**

Hello, i'm trying to sum the values of a query but i get this error.
Basically the query is this: **db.mytable.where(x=> x.id < 5).sum(x=> x.decimalfield ?? 0)**
Can someone help me?
Details below.

Thanks

> Exception message: An unhandled exception of type 'System.Data.SqlClient.SqlException' occurred in Microsoft.EntityFrameworkCore.dll
Stack trace:
   in System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   in System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   in System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   in System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   in System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   in System.Data.SqlClient.SqlDataReader.get_MetaData()
   in System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   in System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   in System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   in System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   in System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   in System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   in System.Data.Common.DbCommand.ExecuteReader()
   in Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
   in Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   in Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.BufferlessMoveNext(Boolean buffer)
   in Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
   in Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, TState state)
   in Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   in Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers)
   in lambda_method(Closure , QueryContext )
   in Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass20_0`1.<CompileQueryCore>b__0(QueryContext qc)
   in Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   in Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   in System.Linq.Queryable.Sum[TSource](IQueryable`1 source, Expression`1 selector)
   in EFCoreDemo.Program.Main(String[] args) in c:\users\user\documents\visual studio 2015\Projects\EFCoreDemo\EFCoreDemo\Program.cs:riga 14
   in System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   in System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   in Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   in System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   in System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   in System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   in System.Threading.ThreadHelper.ThreadStart()

### Further technical details

EF Core version: 1.1
Operating system: Win10 - SqlServer2014
Visual Studio version: 2015

### PR DESCRIPTION
**Pull request by smitpatel**
Fixes #7103 
@anpete 

- Query: Set alias for Expression based alias expression only if inside subquery
- Un-ignore Product.UnitPrice in Northwind to bring in decimal? property
- Add some missing order by and remove assert order due to provider differences in default ordering
- Regenerate northwind.db for sqlite to mirror the SqlServer version
  - __EFMigrationsHistory table has different values
  - Some of the indexes in Sqlite has named differently because index names are global in sqlite

~~Other functions to change - `Max`, `Min`, ~~`Count`~~. Anything else?
Un-ignored decimal property from `Product` if approach is fine then I will change all sql.~~

### CODE REVIEW

**Comment by divega** [comment]
@smitpatel Average may be?

Curious on why the expression ends up this way in the first place.

**Comment by smitpatel** [comment]
@divega - I thought about Average but I couldn't find HandleAverage in relational. It seems that we don't translate average to Sql.

The expression ends up in this way because we alias COALESCE always. That could be another way to look at fixing the issue to do alias-ing only when needed. I will try it out too.

**Comment by divega** [comment]
> because we alias COALESCE always

@smitpatel ah, thanks. I remember vaguely that discussion but not exact problem we were trying to solve with that. Definitively it sounds like the approach we took isn't solid.

> It seems that we don't translate average to Sql.

We should start an issue on adding some missing translations. I think it would be a great issue to have up-for-grabs. Do you know by heart others that are missing?

**Comment by smitpatel** [comment]
@divega - I filed #7190 for average. Its small thing but I wanted to keep it separate from this PR because of complexity involved here. We can use that issue for missing translation. I cannot think of any other missing function translation.

On `Coalesce` we were alias-ing for non-column expression even on top level which was the cause of issue here. I resolved the issue by opting to alias only when needed.

@anpete - Ping for review.
Changes incorporated
- Query: Set alias for Expression based alias expression only if inside subquery
- Un-ignore Product.UnitPrice in Northwind to bring in decimal? property
- Add some missing order by and remove assert order due to provider differences in default ordering
- Regenerate northwind.db for sqlite to mirror the SqlServer version
  - __EFMigrationsHistory table has different values
  - Some of the indexes in Sqlite has named differently because index names are global in sqlite

**Comment by anpete** [comment]
:shipit:

**Pull request merged**
