### PR TITLE
Initial implementation of a MongoDB Provider.

### PR DESCRIPTION
**Pull request by crhairr**
- Wraps the official MongoDB C# driver
 - Builds and tests run from command line (functionality tests require MongoDB 3.2 to be installed).
 - TODO: does not have a Design library or full support for Migrations.
 - TODO: does not have a separate DocumentDB layer similar to the common Relational layer for SQL providers.
 - TODO: add XML comments (currently not present to keep the code clean and legible while building the provider).

Addresses #7243.

### CODE REVIEW

**Comment by rowanmiller** [comment]
This isn't something that our team wants to take on at this stage. If there are any volunteers in the community then we'd certainly be happy to help them take over the project (we work pretty closely with a number of provider writers).

**Comment by EdwardBlair** [comment]
Excellent work! Very interested in this, been looking for a MongoDB provider for a while.  Sorry to see this PR was rejected.

Would you be willing to pop this into a standalone project/repo? I'd do it myself, but I wouldn't want to impose.

**Comment by ErikEJ** [comment]
Happy to help @EdwardBlair - getting this working would also enable access to DocumentDB (as it has a MongeDB surface now)

**Comment by EdwardBlair** [comment]
In its current state it doesn't quite work with EF Core 1.1.1.

It relies on the new class `Microsoft.EntityFrameworkCore.Infrastructure.CoreModelValidator` which depends on an updated version of `ModelValidator` which isn't present in 1.1.1.  It also relies on an updated version of `ModelSource` to pass along the validator.

Fortunately the interfaces they implement haven't changed. I managed to work around this by just copying the related files from EFCore to the new project, putting them in a new namespace and referencing those. Appears to work fine.

Unsure what would be the best course, have custom implementations (i.e. copy them from EFCore) of IModelValidator and IModelSource until EFCore next is released, then remove these classes and reference ones from EFCore. Or modify MongoDBProvider so it works without any Frankenstein-ery.

N.B. I am a complete novice at EFCore or anything on this scale.

**Comment by crhairr** [comment]
I originally wrote this as a standalone against EFCore 1.1 and then migrated it to 1.2 so I could take advantage of some goodies in the develop branch. I've been putting off migrating it back to standalone because EF Core 1.2 is supposed to be released soon, which will mean that the internals won't have to be re-written much.

I'll just have to figure out what to do about the shared project items like Check. Hopefully, I can use Git's submodule mechanism to point to the shared subdirectory in EF Core. That would mean even fewer changes, and would make it very easy for the EF Core team to merge it in if they ever did decide to take over the code.

**Comment by roji** [comment]
@crhairr and others, as someone maintaining another external EF Core provider (Npgsql), I'd strongly advise simply copying the shared project items into your own repo rather than using git submodules. The shared source files really don't change all that often and there's really no reason to go into the complexities of submodules...

It also wouldn't make it harder or easier to merge back into the main EF Core repo if that's ever on the table - which it probably won't be...

**Comment by ErikEJ** [comment]
@crhairr Agree 100% with @roji  here ...

**Comment by crhairr** [comment]
@roji You're probably right on both counts.

@EdwardBlair I'll go ahead and migrate this back to standalone sometime this week and create a new repo for anyone who wants to contribute. I'll copy any missing references for now so that it won't be that big of a pain to rebuild against 1.2 whenever it gets released.

**Comment by crhairr** [comment]
I didn't get around to this until Sunday, but I got it converted this back to a standalone provider: https://github.com/crhairr/EntityFrameworkCore.MongoDb

It references the 1.2.0-preview build of EFCore, so there wasn't much to change aside from the DI. It just took me a little longer than expected to work out the kinks with VS2017 and fix a few tests that were failing with the updated MongoDb driver.

I'll be deleting my fork of this repo.

**Pull request closed without merging**
