### PR TITLE
Disable IncludeSource in projects with IncludeSymbols disabled

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by smitpatel** [comment]
@pranavkm @natemcmaster - Can any of you explain this change?

cc: @divega @ajcvickers

**Comment by pranavkm** [comment]
We enabled `IncludeSource` for symbol packages via the SDK. This broke packing a couple of projects which previously had symbol package generation disabled. I re-disabled it by turning off `IncludeSource`.

**Comment by ajcvickers** [comment]
@smitpatel Is there anything we need to follow up on here?

**Comment by smitpatel** [comment]
@ajcvickers - No

**Pull request merged**
