### PR TITLE
Metadata: Align entity name properties with CLR

### LINKED ISSUE #1613: Metadata: Align entity name properties with CLR
We have EntityType.Name and EntityType.SimpleName. Seems like it would be better just to match CLR here: FullName and Name.

### PR DESCRIPTION
**Pull request by smitpatel**
resolves #1613

### CODE REVIEW

**Comment by ajcvickers** [comment]
@rowanmiller Can you check the API review notes on this one? I thought we came to a different decision.

**Comment by rowanmiller** [comment]
We decided to leave Name as-is and rename SimpleName to DisplayName and make it an extension method (though personally I don't think the extension method part is critical)

**Comment by ajcvickers** [comment]
Thanks Rowan. I think it should be an extension method because then any implementation of the interface can use the same implementation.

**Comment by smitpatel** [comment]
@rowanmiller - Can you update #1613  or close it and file a new issue for this task?

**Comment by rowanmiller** [comment]
@smitpatel - Closed. @anpete is going to be making that changes from the API review.

**Pull request closed without merging**
