### PR TITLE
Use Core CLR System.Data packages

### PR DESCRIPTION
**Pull request by bricelam**

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
:shipit:

**Comment by ErikEJ** [comment]
Where is the source for System.Data.Common and System,Data.SqlClient hosted?

**Comment by bricelam** [comment]
No idea; we don't own it anymore. :wink: I suspect it'll eventually be part of the [dotnet/corefx](https://github.com/dotnet/corefx) repository.

**Comment by ErikEJ** [comment]
@bricelam Thanks! Makes sense...

**Comment by RickyLin** [comment]
How can I get 4.0.0-beta-* package of System.Data.Common? my `build.cmd` failed.

**Comment by bricelam** [comment]
@RickyLin our CI is pretty red :red_circle: at the moment, when everything is green :green_heart: again, it will be available on the regular feed. Until then, you can grab it from the "volatile" feed: https://www.myget.org/F/aspnetvolatile/api/v2/

I haven't tried this, but it might work:

```cmd
kpm restore --fallbacksource https://www.myget.org/F/aspnetvolatile/api/v2/
```

**Comment by bricelam** [comment]
@ErikEJ Confirmed: The spreadsheet linked to on [.NET Core Open Source Update](http://blogs.msdn.com/b/dotnet/archive/2015/01/28/net-core-open-source-update.aspx) lists System.Data.Common and System.Data.SqlClient as .NET Core assemblies to be made available on GitHub.

**Comment by ErikEJ** [comment]
@bricelam Thanks, I noticed that reading that blog post as well - only 25% of .NET Core is currently available on Github!

**Pull request merged**
