### PR TITLE
Upgrade version of dotnet-test-xunit to RC2

### PR DESCRIPTION
**Pull request by natemcmaster**
Also removes unnecessary dependency on Ms.NETCore.Platforms.

cc @pakrym @smitpatel

### CODE REVIEW

**Comment by pakrym** [comment]
`Ms.NETCore.Platforms` is required for 'runable' projects that target `net451`

**Comment by natemcmaster** [comment]
oh, ok. I'll reverse that part of this change

**Comment by smitpatel** [comment]
LGTM

**Comment by natemcmaster** [comment]
This enables the VS test runner. When the new VS tooling becomes public, we can consider again switching back to xproj.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/EntityFramework/commit/809139d6748c837a2ad8e1b0f0a363406725c6d7

**Pull request closed without merging**
