### PR TITLE
Make FromSql query tests provider-agnostic #2941

### PR DESCRIPTION
**Pull request by mikary**
Cleanup for the FromSql tests
@anpete @natemcmaster

### CODE REVIEW

**Comment by natemcmaster** [comment]
Yes, `SqliteUpdateSqlGenerator.DelimitIdentifier`

**Comment by mikary** [comment]
Discussed with @anpete 
* Delimiters were added due to mention of case-sensitivity issue in PostgreSQL described in #2941, if this is still an issue after these changes, we can address at that point
* Schema came from following templating patterns in `SqlGeneratorTestBase`, removed
* There are actually about 3 different provider APIs for SQL generation (to be addressed by #2493)

Updated to remove extra delimiters in original tests, reverting SQL generation pattern.

**Comment by natemcmaster** [comment]
LGTM

**Comment by anpete** [comment]
:shipit:

**Pull request merged**
