### PR TITLE
Disable API check on tests and meta-packages

### PR DESCRIPTION
**Pull request by bricelam**

### CODE REVIEW

**Comment by smitpatel** [comment]
EFCore.Specs.Tests?

**Comment by bricelam** [comment]
Thanks. Was running again to make sure I got them all.

Interestingly, it never even tries to run on the following projects...
* dotnet-ef
* ef

**Comment by smitpatel** [comment]
Should it be running on those projects? Is this due to lack of baseline or just no output from tools (perhaps bug in the tool)?

**Comment by bricelam** [comment]
No output. The others gave a warning about no baseline. Possibly a "feature" for tools, but that shouldn't apply to `ef`...

**Pull request merged**
