### PR TITLE
Sequence as default value generator for SqlServer

### LINKED ISSUE #1811: SqlServer: Default Value Generator
Presently for PK with single property, we put Default as value generation strategy.
This Default annotation translates to value generation defined on model or to Identity.
Instead of setting Identity hard coded, we should have some way to define what should be the default value generation strategy.

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #1811 
Add Model Conventions support
Set Sequence as default value generator for SqlServer by convention

### CODE REVIEW

**Comment by smitpatel** [comment]
Unit tests are not added yet.

**Comment by AndriySvyryd** [comment]
Looks good so far. Remember to test other repos (run "build install" for EF then run "build" in Universe)

**Comment by smitpatel** [comment]
Added tests.
All repos in Universe passing except Helios. (requires older MSBuild which I don't have in my machine)

**Comment by AndriySvyryd** [comment]
:shipit: 
This will likely require dropping databases, so send out an email explaining what changed and how to drop them.

**Comment by rmja** [comment]
@AndriySvyryd, @smitpatel, this PR broke my setup. Every time I try and do an insert a

    SELECT NEXT VALUE FOR DefaultSequence

is sent to the database, failing with `DefaultSequence` not being an object. Is there something I have missed?

**Comment by divega** [comment]
It is likely that you need to drop and recreate the database.

**Comment by rmja** [comment]
@divega, I am not following. I am working on a copy of our production database. Not something generated by ef through migrations.

**Comment by divega** [comment]
@rmja In that case you might need to opt out of using sequences by explicitly specifying that you want to use SQ Server IDENTITY, e.g.:

``` C#
modelBuilder.Entity<Entity>().Property(e => e.Property).ForSqlServer().UseIdentity();
```

**Comment by rmja** [comment]
Thanks @divega, it works! I thought, when trying to solve this myself, that Identity in `UseIdentity()` had something to do with http://www.asp.net/identity. My bad.

**Comment by divega** [comment]
Not your bad :smile: Identity is an overloaded term, so it can unfortunately be a bit confusing. Glad to help.

**Comment by ajcvickers** [comment]
@rmja Note that if you always want SQL Server to use Identity, and not sequences, for properties such as integer primary keys, then you can just call UseIdentity for your model, rather than doing it for each individual property:
```
modelBuilder.ForSqlServer().UseIdentity();
```
The code for this has been updated recently, so please let us know if you try this and it doesn't work.

**Comment by rmja** [comment]
@ajcvickers Yes I found that, and it seems to work fine with the current bits.

**Comment by luisrudge** [comment]
Why was the sequence chosen to be the default strategy?

**Pull request merged**
