### PR TITLE
tree printer rework - reusing build in ExpressionBuilder and storing the TreeNode in internal variable rather than returning it as a result of a Visit

### PR DESCRIPTION
**Pull request by maumar**
@anpete @divega

### CODE REVIEW

**Comment by anpete** [comment]
Hey, did you look at the pretty printer in relinq?

**Comment by maumar** [comment]
Yes I looked at it, and its really nice, just need to do a bit of formatting to make it readable for my taste. However @divega  suggested it would be good to get this thing in regardless (after applying your CR suggestion)

**Comment by anpete** [comment]
@divega Do we need two?

**Comment by divega** [comment]
I talked to @maumar and the differences (or deficiencies) in formating have an impact on his productivity debugging query bugs. So yes, I think temporarily it is reasonable to have two expression printers. Long term we can look at overriding Relinq's and potentially contributing back improvements if they want them.

**Comment by divega** [comment]
BTW @maumar will file a bug to track what we do long term.

**Comment by anpete** [comment]
Sounds good. It would be ideal if we could override relinq's as part of this change.

**Comment by maumar** [comment]
meged ad98141231c8871ed090b039dd657031854aa5c8

**Pull request closed without merging**
