### PR TITLE
RevEng: Make OptionsBuilder Configuration conditional

### LINKED ISSUE #6686: Hard-coded connection string in DB Context after using scaffolding tool
I may be misunderstanding the intent of the tool: once I run `dotnet ef dbcontext scaffold ...`, all of my files are generated as expected, but the provided connection string is hard-coded in the dbcontext class itself (with a warning directing the developer to follow best-practices on storing a connection string).

I had planned to do my database schema updates externally (more specifically from a SQL Server database project), so I will need to run this tool whenever there are any schema changes, which means, each time it runs, I'll have to manually modify the generated database context (or script the change).

Is there an option/pattern I'm missing, or I am not following the intended usage of the tool?

### PR DESCRIPTION
**Pull request by smitpatel**
fix #6686 

Diff for expected files shows generated code.

### CODE REVIEW

**Comment by smitpatel** [comment]
@divega @lajones

**Comment by lajones** [comment]
Looks good. :shipit:

**Comment by ElanHasson** [comment]
When I scaffold using  1.1.2 I do not get the !optionsBuilder.IsConfigured statement. 

Which release will this make it into?

**Comment by smitpatel** [comment]
@ElanHasson - It was fixed in release 2.0.0-preview1

**Comment by ElanHasson** [comment]
Cool, thanks.

**Pull request merged**
