### PR TITLE
Changed package versions to beta2

### PR DESCRIPTION
**Pull request by kichalla**
@bricelam : Just FYI...the Xunit packages are not available on public Nuget feed and we are figuring out if we need to create a separate feed for external packages, but other than that please take a look at the changes to other packages.

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@kichalla__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by bricelam** [comment]
@davidfowl @pranavkm Are there any plans automatically change the stars to fixed versions in the master branch?

**Comment by pranavkm** [comment]
Might be something we want to do as part of branching. Want to file a Universe work item?

**Comment by bricelam** [comment]
Filed aspnet/Universe#159

**Pull request closed without merging**
