### PR TITLE
[WIP] Remove Configuration classes from Scaffolding

### PR DESCRIPTION
**Pull request by smitpatel**
Instead use IModel to write the code files.

### CODE REVIEW

**Comment by bricelam** [comment]
👍 Looking good.

**Comment by ErikEJ** [comment]
@smitpatel Will you give a heads up when this avalanche of changes have settled?

**Comment by smitpatel** [comment]
@ErikEJ  - Certainly. At present, I m creating series of PRs which would merge into single branch. I will give you heads up before I merge it in dev.

**Comment by smitpatel** [comment]
closing in favour of #8583

**Pull request closed without merging**
