### PR TITLE
Rename DbContextOptions to EntityOptions and update all related naming.

### PR DESCRIPTION
**Pull request by ajcvickers**

### CODE REVIEW

**Comment by anpete** [comment]
:shipit:

**Comment by lajones** [comment]
Looks like you missed SqlServerDbContextTemplate.cshtml template in SqlServer.Design which also has a reference to DbContextOptionsBuilder? If you like I can check this in with the E2E test code (which is out for review - see #2257)?

**Comment by ajcvickers** [comment]
@lajones That file has been updated--not sure why you are not seeing it.

**Comment by lajones** [comment]
@ajcvickers Yep - I see it now - though I swear I searched for it 3 times before I sent the comment. Ah, well.

**Pull request merged**
