### PR TITLE
No year before 1753!

### PR DESCRIPTION
**Pull request by ErikEJ**
Fixes issue #2425

### CODE REVIEW

**Comment by ajcvickers** [comment]
@ErikEJ The problem with this change is that I explicitly did use a default DateTime object to make sure it works, at least when it can work. This is because it didn't work out-of-the-box on SQL Server with the old stack and this was a pain point for people. So I think we need a change here that allows the test to continue to verify that this works when it can, but with a provider opt-out if it just isn't possible to make it work for a given provider.

**Comment by ErikEJ** [comment]
@ajcvickers  Ahh, makes sense. How about a property to set the value, and leave it at the default if not set?

**Comment by ajcvickers** [comment]
@ErikEJ Sounds good.

**Comment by ErikEJ** [comment]
@ajcvickers PR updated

**Comment by ajcvickers** [comment]
Thanks Erik. Looks like you missed the override in the in-memory provider, but I added it and merged.

**Comment by ErikEJ** [comment]
@ajcvickers Thanks a lot!

**Pull request closed without merging**
