### PR TITLE
Re-enable skipped design-time tests and remove dead tests

### PR DESCRIPTION
**Pull request by natemcmaster**
Progress towards https://github.com/aspnet/EntityFramework/issues/5346

### CODE REVIEW

**Comment by ajcvickers** [comment]
@natemcmaster So we really have zero skipped tests after this change?

**Comment by ajcvickers** [comment]
Looks like there are skipped tests in:
* InheritanceRelationshipsQueryTestBase
* OptimisticConcurrencyTestBase
* FieldMappingTestBase
* AsyncQueryTestBase
* QueryTestBase
* ComplexNavigationsQueryTestBase
* GearsOfWarQueryTestBase

**Comment by natemcmaster** [comment]
Sorry, should have been more clear. I mean we are re-enabling **some** skipped tests, not all.

**Comment by ajcvickers** [comment]
@natemcmaster That's great, but then it doesn't resolve the issue assigned to Lawrence which was to scan the code for all skipped tests and either re-enable them or check that there is a bug associated with the test and that the skipped test is mentioned from that bug.

**Comment by natemcmaster** [comment]
I edit the description above so #5346 is still open when the PR merges. This re-enabled tests here are only for the tests concerning design-time tools

**Comment by ajcvickers** [comment]
:shipit:

**Pull request merged**
