### PR TITLE
Prettier type names for scaffolded primitive arrays

### PR DESCRIPTION
**Pull request by roji**

### CODE REVIEW

**Comment by bricelam** [comment]
Can we do this in a more general way like in [this code](https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.Design/Migrations/Design/CSharpHelper.cs#L193-L208)?

**Comment by bricelam** [comment]
See also #1671 😉

**Comment by roji** [comment]
Sure, I can generate the entries for the array types from the primitives, is it worth the trouble though? It would also require using `Type.MakeArrayType()`, does that play well with .NET Native etc.?

**Comment by bricelam** [comment]
@roji I think you misunderstood my comment. I'm recommending changing [CSharpUtilities.GetTypeName](https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.Relational.Design/Internal/CSharpUtilities.cs#L364) instead to add something like this:

```C#
if (type.IsArray)
{
    return GetTypeName(type.GetElementType()) + "[]";
}
```

**Comment by bricelam** [comment]
(That way, we don't have to add values to `_primitiveTypeNames`)

**Comment by roji** [comment]
Oops, that was pretty silly of me...

Amended this PR with your suggestion.

**Pull request merged**
