### PR TITLE
Fix bugs in SQLite reveng foreign key

### LINKED ISSUE #2820: Testing: rev-eng for SQLite
Add more extensive testing for SQLite reverse engineering. Current tests only examine simple case.
- [ ] Test custom templates
- [x] Test logging
- [x] More complex databases

### PR DESCRIPTION
**Pull request by natemcmaster**
Handles quirks in SQLite's foreign key behavior which allows FK to a unique index.

Fix bug in model generation.

Adds more testing to bring it up to par with SqlServer.Design testing. Fix #2820

### CODE REVIEW

**Comment by natemcmaster** [comment]
cc: @lajones after this I'll be switching to work on different parts of EF. If there is anything else to add for SQLite reveng or  #2820, let me know.

**Comment by ErikEJ** [comment]
@lajones  I assume you know that SQL Server also allows foreign keys to a unique index (instead of a primary key) ?

**Comment by natemcmaster** [comment]
On a related note, should we reverse engineering generate keys in the metadata for each unique index on a table?

**Comment by lajones** [comment]
@ErikEJ @natemcmaster - raised issue #2840 to consider issues raised by alternate keys / indexes etc.

**Comment by lajones** [comment]
@natemcmaster other than the issues raised in #2840 - I would make sure you are testing all nullable and non-nullable data types that SQLite supports, and composite keys. SQLite also raises the issue of what happens if say a string is stored in a column which is nominally an integer, does that affect reveng at all?

**Comment by lajones** [comment]
:shipit: Looking through - it looks like you already covered what I was suggesting above.

**Comment by natemcmaster** [comment]
@lajones thanks. It's worth mentioning here that we are only reverse engineer the column types from the CREATE statements. Although we could be more rigorous by analyzing the actual data, that's a rabbit hole I don't want to go down. For now, we do the simple thing in choosing clr types.

**Pull request merged**
