### PR TITLE
Upgrade Roslyn to 2.3.0-beta4-*

### PR DESCRIPTION
**Pull request by mikeharder**

### CODE REVIEW

**Comment by smitpatel** [comment]
side question can a shipping package rtm version depend on pre-release version of dependency?

**Comment by mikeharder** [comment]
@smitpatel: The Roslyn version will be upgraded again to `2.3.0` (final version) before .NET Core 2.0 RTM.  We're upgrading to `2.3.0-beta4-*` now, since the final `2.3.0` won't be available until tomorrow, but we want to find issues as early as possible.

**Comment by smitpatel** [comment]
I assume that we will be pinning most of our dependencies (at least the ones being used in source, before we make final package for RTM release?

**Comment by mikeharder** [comment]
@smitpatel: Correct.

CC: @pranavkm

**Pull request merged**
