### PR TITLE
Include()/ThenInclude() internal rework to have navigations be a tree instead of flat list

### LINKED ISSUE #4490: Request for "AlsoInclude"  (peer level)
I like the Include().ThenInclude() syntax of EF7.   It would also be great if there was an "AlsoInclude" so that when you want to include another peer several levels deep, you don't have to start at the top (with Include) again.  You start getting these really long statements with many include, then include, then include  (back to) include, then include, then include, then include,  etc.  Not a big deal or nothing.  It works as is, but syntactically could certainly be more readable if we had a peer level include  (ie, whatever entity the last include or ThenInclude was referencing).

### LINKED ISSUE #4900: Repeated joins on repeated .Include().ThenInclude()
Working with RC1

Assuming the sample schema:
DB contains Forums
Forum has many Users
Forum has many Posts
Post has many Comments

The code:
```
				var res3 = db.Users
					.Include(u => u.Forum)
					.Include(u => u.Forum)
					.ToList();
```

Generates the query:

```
SELECT [u].[UserId], [u].[ForumId], [u].[Name], [f].[ForumId], [f].[Name], [f0].[ForumId], [f0].[Name]
FROM [User] AS [u]
INNER JOIN [Forum] AS [f] ON [u].[ForumId] = [f].[ForumId]
INNER JOIN [Forum] AS [f0] ON [u].[ForumId] = [f0].[ForumId] <====
```

While this sample may seem fake, it is less so in this case, using .ThenInclude():
```
				var res5 = db.Users.Where(u => u.Name == "user1")
					.Include(u => u.Forum).ThenInclude(f => f.Posts)
					.Include(u => u.Forum).ThenInclude(f => f.Users)
					.ToList();
```

Which generates:
```
SELECT [u].[UserId], [u].[ForumId], [u].[Name], [f].[ForumId], [f].[Name], [f0].[ForumId], [f0].[Name]
FROM [User] AS [u]
INNER JOIN [Forum] AS [f] ON [u].[ForumId] = [f].[ForumId]
INNER JOIN [Forum] AS [f0] ON [u].[ForumId] = [f0].[ForumId] <====
WHERE [u].[Name] = 'user1'
ORDER BY [f].[ForumId], [f0].[ForumId]
```
And also:
```
SELECT [u].[UserId], [u].[ForumId], [u].[Name]
FROM [User] AS [u]
INNER JOIN (
    SELECT DISTINCT [f].[ForumId], [f0].[ForumId] AS [ForumId0]
    FROM [User] AS [u]
    INNER JOIN [Forum] AS [f] ON [u].[ForumId] = [f].[ForumId]
    INNER JOIN [Forum] AS [f0] ON [u].[ForumId] = [f0].[ForumId] <====
    WHERE [u].[Name] = 'user1'
) AS [f0] ON [u].[ForumId] = [f0].[ForumId0]
ORDER BY [f0].[ForumId], [f0].[ForumId0]
```
And then:
```
SELECT [p].[PostId], [p].[ForumId], [p].[Title]
FROM [Post] AS [p]
INNER JOIN (
    SELECT DISTINCT [f].[ForumId]
    FROM [User] AS [u]
    INNER JOIN [Forum] AS [f] ON [u].[ForumId] = [f].[ForumId]
    WHERE [u].[Name] = 'user1'
) AS [f] ON [p].[ForumId] = [f].[ForumId]
ORDER BY [f].[ForumId]
```

Is this a bug or am I doing something wrong?

### PR DESCRIPTION
**Pull request by multiarc**
```
Summary of the changes
-  Include duplicates in query fix, reworked include specifications to be tree like structure of navigations, a lot of associated changes done to make it work.
-  Includes API remains unchanged.
-  A lof of SQL Gen Tests containing multiple Includes should fail after this change, so they all should be reworked.

Fixes #4900
Closes #4490 as no API change needed to resolve duplicates internally
```

**Please check if the PR fulfills these requirements**
- [ ] The code builds and tests pass (verified by our automated build checks)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Code meets the expectations our engineering guidelines. https://github.com/aspnet/Home/wiki/Engineering-guidelines.

Please review the guidelines for CONTRIBUTING.md for more details.

### CODE REVIEW

**Comment by wangkanai** [comment]
For the example of code with `Include()` and `ThenInclude()`
```
public List<Category> GetCategories(Visibility visibility)
{
    return _context.Categories
        .Include(category => category.Sections)
        .ThenInclude(section => section.Articles)                
        .Where(x=>x.Visibility.Show(visibility))
        .ToList();
}
```
Its this tree navigation you are talking about?

profiler-trips

- trip 1

```
SELECT [category].[Id], [category].[Created], [category].[Description], [category].[Order], [category].[Title], [category].[Updated], [category].[UserId], [category].[Visibility]
FROM [Categories] AS [category]
ORDER BY [category].[Id]
```

- trip 2

```
SELECT [s].[Id], [s].[CategoryId], [s].[Created], [s].[Description], [s].[Order], [s].[Title], [s].[Updated], [s].[UserId], [s].[Visibility]
FROM [Sections] AS [s]
WHERE EXISTS (
    SELECT 1
    FROM [Categories] AS [category]
    WHERE [s].[CategoryId] = [category].[Id])
ORDER BY [s].[CategoryId], [s].[Id]
```

- trip 3
```
SELECT [a].[Id], [a].[Created], [a].[Description], [a].[DisableComments], [a].[Draft], [a].[FollowId], [a].[Outdated], [a].[Promoted], [a].[SectionId], [a].[Title], [a].[Updated], [a].[UserId], [a].[Visibility]
FROM [Articles] AS [a]
INNER JOIN (
    SELECT DISTINCT [s].[CategoryId], [s].[Id]
    FROM [Sections] AS [s]
    WHERE EXISTS (
        SELECT 1
        FROM [Categories] AS [category]
        WHERE [s].[CategoryId] = [category].[Id])
) AS [s0] ON [a].[SectionId] = [s0].[Id]
ORDER BY [s0].[CategoryId], [s0].[Id]
```

**Comment by multiarc** [comment]
@wangkanai this example will work the same in original EF and with this PR. 
Include trees needed when you have duplicates, for example:
```csharp
public List<Category> GetCategories(Visibility visibility)
{
    return _context.Categories
        .Include(category => category.CategoryDetails)
        .ThenInclude(details => details.UserEdited)
        .Include(category => category.CategoryDetails) //duplicate here
        .ThenInclude(details => details.UserCreated)
        .Where(x=>x.Visibility.Show(visibility))
        .ToList();
}
```
This will result in two joins of CategoryDetails in original EF and single join with this PR.
This correct on all levels of Include()/ThenInclude() and for every query trip so this PR would resolve all paths and deduplicate it.

By the way it's not obvious why this is bad, but two joins on every trip produces twice more projected fields (for every join) and more data will out of Server and by the way twice more data should be materialized.

**Comment by anpete** [comment]
@multiarc This approach looks good. Are you good with me using this PR as a starting point so I can address the build/rebase/test issues etc.?

**Comment by multiarc** [comment]
@anpete Yes, lets do this.

**Comment by anpete** [comment]
@multiarc Looks like Include is broken in the in-memory provider by this. Are you able to take a look? :smile:

**Comment by multiarc** [comment]
@anpete yes, later today or tomorrow I could look.

**Comment by multiarc** [comment]
@anpete added basic fixes for in memory provider still has some issues with group join include. Can we review and understand whats up?
```csharp
queryContext.QueryBuffer
                .Include(
                    queryContext,
                    source,
                    includeSpecification,
                    relatedEntitiesLoaders,
                    querySourceRequiresTracking);
```
**source** entity is null here for some reason.

**Comment by rowanmiller** [comment]
@multiarc we just wanted to check in and see if you were planning to keep working on this contribution?

**Comment by multiarc** [comment]
@rowanmiller yes I could continue on this. Maybe you can help me understanding what's up with the issue I described above? Doesn't looks like the issue from the Include/ThenInclude rework itself. Also seems I need to merge changes into latest code base, should I do that?

**Comment by rowanmiller** [comment]
@anpete took a look at the issue you described but wasn't able to see anything obvious. This is something you would need to spend some more time debugging. Though there is always the possibility that the code base has moved on enough that it's not still an issue 😄. 

BTW you should rebase on the `feature/1.2.0` branch as this change would be going into 1.2.0 and `dev` is being used for `1.1.0` still.

**Comment by rowanmiller** [comment]
Closing, but we would be willing to take this if you are able to make progress on it. 

I do just want to acknowledge that we have not been very responsive on this PR (my fault) so I understand that this may be frustrating after so much time.

**Pull request closed without merging**
