### PR TITLE
SQLite: Generate proper Guid literals

### LINKED ISSUE #5801: SQLite Query: Guid literals are wrong
This works on SQL Server, but not on SQLite.
```C#
public class GuidKey
{
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public Guid Id { get; set; }

    public string Foo { get; set; }
}

public class FindContext : DbContext
{
    public DbSet<GuidKey> GuidKeys { get; set; }
}

[Fact]
public virtual void Find_guid_key()
{
    using (var context = new FindContext())
    {
        context.Add(
            new GuidKey 
            {
                Id = new Guid("{3FDFC4F5-AEAB-4D72-9C96-201E004349FA}"), 
                Foo = "Smokey" 
            });

        context.SaveChanges();
    }

    using (var context = new FindContext())
    {
        var entity = context.GuidKeys.FirstOrDefault(
            e => e.Id == new Guid("{3FDFC4F5-AEAB-4D72-9C96-201E004349FA}"));

        Assert.Null(entity); // Not found

        entity = context.GuidKeys.ToList().FirstOrDefault(
            e => e.Id == new Guid("{3FDFC4F5-AEAB-4D72-9C96-201E004349FA}"));

        Assert.NotNull(entity); // Found by LINQ to Objects
    }
}
```
```sql
PRAGMA foreign_keys=ON;

SELECT "e"."Id", "e"."Foo"
FROM "GuidKey" AS "e"
WHERE "e"."Id" = '3fdfc4f5-aeab-4d72-9c96-201e004349fa'
LIMIT 1
```

### PR DESCRIPTION
**Pull request by bricelam**
Fixes #5801

### CODE REVIEW

**Comment by ajcvickers** [comment]
:shipit:

**Comment by anpete** [comment]
Anything to re-enable for #5801?

:shipit:

**Comment by ajcvickers** [comment]
@anpete I didn't check in/disable anything for #5801. I found it writing tests for Find, but I just changed the tests to not use GUIDs after finding the bug. I think it would be good to have some functional tests that make use of GUID literals, but it doesn't seem essential.

**Comment by IDisposable** [comment]
:shipit:

**Pull request merged**
