### PR TITLE
Made Logger extensions public

### PR DESCRIPTION
**Pull request by ErikEJ**
Fixes #1958

### CODE REVIEW

**Comment by rowanmiller** [comment]
@ErikEJ per comment on the original request from @roji 
> given that we are making this class public can you make sure we check parameters for null on all public methods and move it to the  Microsoft.Data.Entity.Relational  namespace.

**Comment by ErikEJ** [comment]
@rowanmiller  Yes, I saw that, where is that not the case in this PR - I looked but could not find any place...?

**Comment by ErikEJ** [comment]
@anpete @rowanmiller PR updated

**Comment by rowanmiller** [comment]
@ErikEJ yep that's what we meant. @anpete can you process this one now.

**Comment by ErikEJ** [comment]
@anpete PR updated with latest changes in dev

**Pull request merged**
