### PR TITLE
Bring anonymous property casing inline with Diagnostics Source usage recommendations

### PR DESCRIPTION
**Pull request by avanderhoorn**

### CODE REVIEW

**Comment by avanderhoorn** [comment]
// @rynowak @divega @anpete

**Comment by rynowak** [comment]
The suggestion here is to make these camelCase instead of PascalCase. It's more natural for consumers to write it that way and the consumers are the ones that have the harder job of matching things up correctly.

**Comment by anpete** [comment]
This is unfortunate. Why can't it just be case insensitive?

**Comment by divega** [comment]
I agree with @anpete. Why is camelCase more natural by the way?

**Comment by anpete** [comment]
@divega I think because the props are mapped to arguments on the consumer side.

**Comment by rynowak** [comment]
It's more natural because the consumer is going to write a method definition, and they would typical write the arguments that way.

> This is unfortunate. Why can't it just be case insensitive?

These are programmatic identifiers. Making the top level items case-insensitive makes it seem like other parts of the system should be case-insensitive, which ends with you having case-insensitive properties on the proxy objects themselves. I'd rather not go down that route.

**Comment by anpete** [comment]
As @avanderhoorn has discovered, this seems like a pit of failure. It needs to be idiomatic on both sides.

**Comment by rynowak** [comment]
Actually, yeah that makes a little sense to think of it that way. Idiomatic for both sides. OK I'm convinced.

**Comment by avanderhoorn** [comment]
Closing this off given that @rynowak is going to be making the changes at his end.

**Pull request closed without merging**
