### PR TITLE
Make DatabaseGeneratedOption.Identity not throw for non-integer properties on SQL Server

### LINKED ISSUE #7010: [DatabaseGenerated(DatabaseGeneratedOption.Identity)] incorrectly configures the column as SqlServer identity
### Steps to reproduce
I tried using the `[DatabaseGenerated(DatabaseGeneratedOption.Identity)]` attribute on a DateTime (which has a default value constraint on the column) as described in the [Generated Properties](https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties) documentation and I got an error as shown below:

Personally I think the documentation is wrong, as the `[DatabaseGenerated(DatabaseGeneratedOption.Identity)]` attribute is pretty specific. I successfully used the Fluent API  .ValueGeneratedOnAdd() to tell EF Core there was a default value constraint.

### The issue
1. Create a table with a column 'DateOfBirth' with a default constraint on a `[datetime2]` column, e.g.  
```
[DateOfBirth] [datetime2](7) NOT NULL DEFAULT ('2000-01-01T00:00:00.000'),
```
2. Map that column to a property 'DateOfBirth'
3. Use the `[DatabaseGenerated(DatabaseGeneratedOption.Identity)]`  attribute to tell EF Core that the column has a default constraint.
4. Create the DbContext and it fails with the following stack trace

```
Exception message: Identity value generation cannot be used for the property 'DateOfBirth' on entity type 'PersonWithAddUpdateAttibutes' because the property type is 'DateTime'. Identity value generation can only be used with signed integer properties.
Stack trace:
   at Microsoft.EntityFrameworkCore.Metadata.SqlServerPropertyAnnotations.SetValueGenerationStrategy(Nullable`1 value)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.SqlServerPropertyBuilderAnnotations.ValueGenerationStrategy(Nullable`1 value)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.SqlServerValueGenerationStrategyConvention.Apply(InternalPropertyBuilder propertyBuilder, DatabaseGeneratedAttribute attribute, MemberInfo clrMember)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyAttributeConvention`1.Apply(InternalPropertyBuilder propertyBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnPropertyAdded(InternalPropertyBuilder propertyBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.AddProperty(String name, Type propertyType, MemberInfo memberInfo, ConfigurationSource configurationSource, Boolean runConventions)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType.AddProperty(MemberInfo memberInfo, ConfigurationSource configurationSource, Boolean runConventions)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(Property existingProperty, String propertyName, Type propertyType, MemberInfo clrProperty, Nullable`1 configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(String propertyName, Type propertyType, MemberInfo clrProperty, Nullable`1 configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(MemberInfo clrProperty, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyDiscoveryConvention.Apply(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnEntityTypeAdded(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(EntityType entityType, Boolean runConventions)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(Type type, ConfigurationSource configurationSource, Boolean runConventions)
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity(Type type)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.FindSets(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.RelationalModelSource.FindSets(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_StateManager()
   at Microsoft.EntityFrameworkCore.DbContext.EntryWithoutDetectChanges[TEntity](TEntity entity)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at test.UnitTests.TestPeopleContext.TestPeopleContextExistingDatabaseOk() in C:\Users\Jon\Documents\Visual Studio 2015\Projects\EfCoreInAction\test\UnitTests\TestPeopleContext.cs:line 111
```

### Further technical details

EF Core version: "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0-preview1-final",
Operating system: Windows 10
Visual Studio version: VS2015 update 3

Other details about my project setup:

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Make DatabaseGeneratedOption.Identity only set ValueGenerated to OnAdd
Don't set RequiresValueGenerated when configuring Identity on a property
Add a convention to set RequiresValueGenerated when using Sequence or a custom value generator

Fixes #7010

### CODE REVIEW

**Comment by ajcvickers** [comment]
Why does SqlServerValueGenerationStrategyConvention set the ValueGeneratedStrategy? When we discussed in triage we though the behavior of DatabaseGeneratedOption.Identity was just to mark the property as ValueGeneratedOnAdd. In other words, it doesn't mean use Identity over Sequence, for example. And it means it works correctly for Guids where there is no Identity/Sequence distinction. This matches the behavior we had in EF6. Did we make an explicit decision to add more semantics to the annotation for SQL Server in EF Core?

**Comment by AndriySvyryd** [comment]
Because it's confusing that it doesn't, see https://github.com/aspnet/EntityFramework/issues/6426

**Comment by AndriySvyryd** [comment]
Updated. The behavior now matches the docs and #6426 is fixed by updating RequiresValueGenerated through a convention.

**Comment by ajcvickers** [comment]
image

**Comment by AndriySvyryd** [comment]
Encoding issue. Updated.

**Comment by AndriySvyryd** [comment]
Reworking this... again...

**Pull request closed without merging**
