### PR TITLE
[SMALL] Generated DbContext classes need "using System;"

### PR DESCRIPTION
**Pull request by lajones**
Fix for #5238. One file is the fix - the rest are just updating the expected results.

### CODE REVIEW

**Comment by lajones** [comment]
Put `providers-beware` on this because if you have tests which check the contents of generated files for your providers you will have an extra `using System;` line.

**Comment by smitpatel** [comment]
Is there a way to find out only necessary imports? I think Migration files use that approach.

**Comment by ErikEJ** [comment]
Thanks, @lajones

**Comment by natemcmaster** [comment]
:shipit:

@smitpatel we could try to detect what we need, but this simple fix is simple IMO. Migrations has all that detection b/c migration scaffolding may pull in user types, but dbcontext scaffolding doesn't rely on existing user code.

**Comment by lajones** [comment]
Agree with @natemcmaster - trying to keep it simple. Checked in with commit 4e27d5a.

**Pull request closed without merging**
