### PR TITLE
Implement IListSource on LocalView and EntityQueryable to further direct data binding

### PR DESCRIPTION
**Pull request by ajcvickers**
Issues #8898 #8899

### CODE REVIEW

**Comment by ajcvickers** [comment]
No, would it change the decision to do this depending on the answer?

**Comment by divega** [comment]
> No, would it change the decision to do this depending on the answer?

No, I think this PR is fine regardless. 

What I am still concerned about is the decision to deviate from what we had in EF6. I.e. .Local used to returned an ordered collection that could be used directly for WPF-like databinding but now you need another call to `ToObservableCollection()` which won't be discoverable unless in binding to these objects directly causes the exception.

**Comment by divega** [comment]
That is why #8898 says 

> ... but we also need to verify that doing so will help for WPF.

**Comment by ajcvickers** [comment]
I'll leave #8898 open after merging this and we can bring it back to triage to discuss the priority of doing this investigation.

**Pull request merged**
