### PR TITLE
Update SQLitePCLRaw to 1.1.6

### PR DESCRIPTION
**Pull request by natemcmaster**
React to changes in Microsoft.Data.Sqlite

### CODE REVIEW

**Comment by natemcmaster** [comment]
Hit a few test failures locally. Any ideas @bricelam  or @anpete?
```
[xUnit.net 00:00:13.6345388]     Microsoft.EntityFrameworkCore.Query.InheritanceRelationshipsQuerySqliteTest.Nested_include_with_inheritance_reference_reference3 [FAIL]
[xUnit.net 00:00:13.6362974]       Assert.Equal() Failure
[xUnit.net 00:00:13.6364268]       Expected: 3
[xUnit.net 00:00:13.6365036]       Actual:   6
[xUnit.net 00:00:13.6377385]       Stack Trace:
[xUnit.net 00:00:13.6403141]            at Microsoft.EntityFrameworkCore.Query.InheritanceRelationshipsQueryTestBase`2.Nested_include_with_inheritance_reference_reference3()

[xUnit.net 00:00:13.8900139]     Microsoft.EntityFrameworkCore.Query.InheritanceRelationshipsQuerySqliteTest.Nested_include_with_inheritance_reference_reference1 [FAIL]
[xUnit.net 00:00:13.8902010]       Assert.Equal() Failure
[xUnit.net 00:00:13.8902729]       Expected: 6
[xUnit.net 00:00:13.8903342]       Actual:   12
[xUnit.net 00:00:13.8904133]       Stack Trace:
[xUnit.net 00:00:13.8904990]            at Microsoft.EntityFrameworkCore.Query.InheritanceRelationshipsQueryTestBase`2.Nested_include_with_inheritance_reference_reference1()

**Comment by smitpatel** [comment]
I triggered the run again. But based on test and seed data, this should never happen, unless seeding was faulty.

**Comment by natemcmaster** [comment]
The test failure was pretty consistent. Happened on a local build, Travis and AppVeyor.

**Comment by smitpatel** [comment]
Does it happen for SqlServer?

**Comment by natemcmaster** [comment]
SqlServer tests on .NET Core pass. .NET Framework tests are failing for me, but for different reasons. ( #8896 )

**Comment by smitpatel** [comment]
- Since SqlServer tests are passing means SQLite seeding is doing something wrong. Try running tests without this package upgrade.
- net461 test failure is due to test host deciding a fancy place to create scratch db. If you use dotnet from %userprofile%/.dotnet folder it will work 😛

**Comment by natemcmaster** [comment]
> Try running tests without this package upgrade.

Tests pass just fine.

**Comment by smitpatel** [comment]
Then looks like there is some issue with the package.

**Comment by natemcmaster** [comment]
SQLitePCLRaw 1.1.6 includes SQLite 3.19.3. SQLitePCLRaw 1.1.3 included SQLite 3.16.0. Looks like the SQLite update includes changes to JOINs that may affect query results:
http://sqlite.org/releaselog/3_19_3.html

I don't have time to dig deep into EF to figure out what has changed here. @ajcvickers - who could take on the investigation of what's broken in query? Should I open a new issue to investigate?

**Comment by ericsink** [comment]
So apparently I threw you guys a curve ball by updating my sqlite builds.  Sorry about that.  :-(

I'm really curious what the problem is.

**Comment by natemcmaster** [comment]
Closing. This version of SQLite bundled in this update appears to includes a regression in LEFT JOIN. Let's not update until we have a fix or a different bundled version.

**Pull request closed without merging**
