### PR TITLE
Suppress obsolete warning for TelemetrySource (temporarily)

### PR DESCRIPTION
**Pull request by anpete**

### CODE REVIEW

**Comment by anpete** [comment]
cc @bricelam is case I did this incorrectly :fried_shrimp:

**Comment by bricelam** [comment]
Hmm, I don't see an [option for noWarn](https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Runtime/ProjectReader.cs#L453-L474); this may not be supported in `project.json`

**Comment by bricelam** [comment]
...but we get [three suppressed](https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Compilation.CSharp.Common/CompilerOptionsExtensions.cs#L28-L30) for free.

**Comment by bricelam** [comment]
Ah, we want #2042

**Comment by bricelam** [comment]
:shipit: (can remove them from `project.json` if you want)

**Comment by anpete** [comment]
Thanks @bricelam will use #pragma I guess.

**Comment by Eilon** [comment]
Do we have a bug to track moving to the new DiagnosticsSource and removing the `#pragmas`?

**Pull request closed without merging**
