### PR TITLE
Add transitive reference to PlatformAbstractions

### PR DESCRIPTION
**Pull request by ryanbrandenburg**

### CODE REVIEW

**Comment by divega** [comment]
Hey @ryanbrandenburg, can you explain why this is needed and also why it is not in release?

**Comment by ryanbrandenburg** [comment]
It's needed because PlatformAbstractions was removed as a transitive dependency from a couple of packages that these packages depend on, and it's causing the CoreCLR gate to fail.

As for being in some branches but not in others, we noticed a problem when I pushed to release, someone had force pushed and @pranavkm lost some commits. He's working on it now and I'll take things back into dev when he's got that all resolved.

**Comment by ryanbrandenburg** [comment]
@pranavkm already merged this in for me.

**Comment by ryanbrandenburg** [comment]
@pranavkm already merged this in for me.

**Pull request closed without merging**
