### PR TITLE
#2203 Switch test projects to .NET 4.6…

### PR DESCRIPTION
**Pull request by MichaelKetting**
… to enable use of features such as settable CultureInfo.CurrentCulture/CurrentUICulture properties.

This is in response to @divega and @bricelam suggesting the switch in #2160.

### CODE REVIEW

**Comment by bricelam** [comment]
You'll also need to update the `project.json` files from `dnx451` to `dnx46`.

**Comment by MichaelKetting** [comment]
Ah, thanks. Hmm... got the following error now on the console via build.cmd:

System.InvalidOperationException: The current runtime target framework is not compatible with 'EntityFramework.Commands.FunctionalTests'.

Current runtime Target Framework: 'DNX,Version=v4.5.1 (dnx451)'
  Type: CLR
  Architecture: x86
  Version: 1.0.0-beta5-11735

Where else do I have to set the FX version? Right now, I've just switched the framework-identifier in the project.json file for the test projects. The production projects still read 'dnx45' and list the assemblies.

**Comment by bricelam** [comment]
Interesting. As far as I know, dnx451 packages are compatible with dnx46 projects. I'll investigate more.

**Comment by Eilon** [comment]
@bricelam I'm pretty sure they *should* be compatible... that's the whole idea :smile: Can ask a package person for more info on this... I think maybe @anurse implemented some of the "what's compatible with what" logic.

**Comment by MichaelKetting** [comment]
@Eilon I just pushed the project.json changes into the PR as well so you guys have the full story available :smile: 
Also noticed that yeah, back with dnx45 and dnx451 there was no problem with having different framework versions. I can't rule out that I'm just missing some setting with dnvm etc but I am using the beta 5 clr, so...

**Comment by davidfowl** [comment]
dnx46 doesn't work yet

**Comment by MichaelKetting** [comment]
@davidfowl Ah, thanks, that's good to know. 
@bricelam, @divega  So, should I shelve this PR until later and we keep using .NET 4.5 and Thread.CurrentCulture over on #2160 for the time being?

**Comment by divega** [comment]
Ok. If there are currently no aync tests which depend on culture Thread.CurrentCulture should work for now. Thanks!

**Comment by MichaelKetting** [comment]
Closing PR until dnx46 is available.

**Pull request closed without merging**
