### PR TITLE
Don't create space-only lines in IndentedStringBuilder (Fixes #654)

### LINKED ISSUE #654: IndentedStringBuilder shouldn't create space-only lines
Steps
=====
```C#
var builder = new IndentedStringBuilder();
using (builder.Indent())
    builder.AppendLine();
return builder.ToString();
```
Result
======
```C#
"    \r\n"
```

Expected
========
```C#
"\r\n"
```
The extra characters are a waste of *space*. :wink: We currently use `IndentedStringBuilder` in the following areas.
* Migrations
    * Code
    * DDL
* Query
    * SQL

### PR DESCRIPTION
**Pull request by fujiy**

### CODE REVIEW

**Comment by fujiy** [comment]
The cla process is the same for MSFT employees?

**Comment by bricelam** [comment]
@fujiy You rock. :shipit:

**Comment by rowanmiller** [comment]
Hey All,

Just a quick note to let you know that we will be merging contributions from folks outside the EF team here at Microsoft shortly. We just need to hold off for a little longer while we branch for our next release. There is some process around shipping external contributions with Visual Studio, so we need to branch for our next pre-release before taking any further contributions.

~Rowan

**Comment by bricelam** [comment]
Merged as efa442ff76587dbc0c654d17b8a130fc4bea0480

**Pull request closed without merging**
