### PR TITLE
Updating to RTM builds of xunit and Moq

### PR DESCRIPTION
**Pull request by pranavkm**
cc @ajaybhargavb \ @natemcmaster

### CODE REVIEW

**Comment by ajaybhargavb** [comment]
:shipit:

**Comment by natemcmaster** [comment]
Build started failing for desktop .NET. Any ideas what's wrong?
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'xunit.runner.utility.desktop, Version=2.2.0.3300, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
[00:38:14][Step 2/2]    at Xunit.Runner.DotNet.Program..ctor()
[00:38:14][Step 2/2]    at Xunit.Runner.DotNet.Program.Main(String[] args)
```

**Comment by pranavkm** [comment]
Is this running `dotnet test`?

**Comment by natemcmaster** [comment]
It runs "dotnet-test-xunit.exe" in the output folder of "dotnet publish"

**Comment by lajones** [comment]
@pranavkm I was investigating the failure that was happening before you checked in (the 2 SQLServerE2ETests failing), but now the tests don't run at all. Can you let me know when the problem with XUnit is solved and you're back to those 2 tests failing and I'll take over again? Thanks.

**Comment by natemcmaster** [comment]
Turns out that although this passes locally, efci wasn't picking up the new version of xunit. I've updated the efci version and the tests run now.

**Comment by natemcmaster** [comment]
> Is everything sorted in that case?

Yes. Clearing caches ftw.

**Comment by lajones** [comment]
@pranavkm Yes - I'll take over trying to fix now. Thanks.

**Pull request merged**
