### PR TITLE
fix #8590 - Add DateAdd support for DatetimeOffset

### LINKED ISSUE #8590: Dose EF Core Support `DateAdd` ?
`DateTime.AddMinutes()` and `DateTimeOffset.AddMinutes()` dosn't translate to sql

### Steps to reproduce

```c#
//model
    public class Show
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime StartTime { get; set; }
        public TimeSpan DurationAsTimeSpan { get; set; }
        public int DurationAsInt32 { get; set; }  //minutes , same as DurationAsTimeSpan , juset for test
    }

//linq 
var y = _db.Shows.Where(r => r.StartTime.AddMinutes(r.DurationAsInt32) > dt ).ToList();

//and this is the out sql 
/*
SELECT [r].[Id], [r].[DurationAsInt32], [r].[DurationAsTimeSpan], [r].[StartTime], [r].[Title]
FROM [Shows] AS [r]
*/
```

### Further technical details
EF Core version: 1.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: win7-x64
IDE:  Visual Studio 2017

### PR DESCRIPTION
**Pull request by pmiddleton**
Adds DateAdd support for DatetimeOffset datatype in Sql Server.  Fixes issue #8590

### CODE REVIEW

**Comment by smitpatel** [comment]
@pmiddleton - Preview2 is done for check-ins unless very critical ones. All new work goes to dev now. Can you also add more tests. (one for each function)

**Comment by pmiddleton** [comment]
@smitpatel - Will do.

**Comment by anpete** [comment]
Anything can be done on SQLite? cc @bricelam

**Comment by pmiddleton** [comment]
@smitpatel  - Unit tests added and rebased onto dev.

@anpete  - I don't believe SQLite has an equivalent of DatetimeOffset.

**Comment by bricelam** [comment]
> Anything can be done on SQLite?

See my notes on [DateTime functions](https://github.com/aspnet/EntityFramework/issues/4108#issuecomment-279837564), but these won't work on `DateTimeOffset` without losing timezone information.

**Comment by smitpatel** [comment]
Since we don't have function translator for DateTime in SQLite yet, we can decide for DateTimeOffset while implementing that. I added note in the issue.

@pmiddleton - Can you rebase on dev? There are some conflicts.

**Comment by pmiddleton** [comment]
Done

**Comment by anpete** [comment]
@smitpatel Is this good to go? Can you merge?

**Comment by smitpatel** [comment]
Merged via f25180fbca6b9627832ae0cbbafeefe47994791a

Thanks for contribution.

**Pull request closed without merging**
