### PR TITLE
[2.0.0-preview1] Upgrade to System.Data.SqlClient package 4.4.0-*

### PR DESCRIPTION
**Pull request by smitpatel**
Add switch to use native code for localdb
Port #8291 to 2.0.0-preview1

@ajcvickers @Eilon @muratg for approval.

### CODE REVIEW

**Comment by muratg** [comment]
cc @mikeharder

**Comment by mikeharder** [comment]
Agreed we cannot ship preview1 until tests pass without `System.Data.SqlClient.UseLegacyNetworkingOnWindows`.

**Comment by Eilon** [comment]
@smitpatel / @ajcvickers - If this gets merged, please log a bug in the 2.0.0-preview1 milestone to track undoing the switch.

**Comment by mikeharder** [comment]
This change was actually merged to dev before preview1.  There are currently some test failures in Win2012-Universe in the dev branch related to EF, so we *should not* merge to preview1 at this time.

I believe the root cause is other tests which use EF, outside the EF repo, would need the `System.Data.SqlClient.UseLegacyNetworkingOnWindows` workaround.  And there may be too many impacted tests for the workaround to be feasible.

A few options:

1. Revert this change in Dev, and don't merge until `SqlClient` itself is updated so we no longer need the `System.Data.SqlClient.UseLegacyNetworkingOnWindows` workaround.
2. Temporarily set `System.Data.SqlClient.UseLegacyNetworkingOnWindows` in EF product code so all users of EF get the workaround.

**Comment by Eilon** [comment]
In theory the bug in SqlClient was fixed late last night, so today we might get a build with it fixed.

**Comment by smitpatel** [comment]
Changed the base.
For the options mentioned by @mikeharder,
I initially tried option 2, changing code in product to set the switch before opening connection but that did not work well. Test were still hanging with it. Probably tests were using connection opening themselves. Changing product code to set the switch may not fix all other repos depending on its test infra & regardless its not guaranteed that user will never open connection themselves without using EF. (User can pass already open connection to EF), hence after discussing with @ajcvickers , we went with only test code changes to make EF pass. This fix does not guarantee that products using EF will not hang until SqlClient is fixed.

As @Eilon mentioned above, since the bug is already fixed, we should remove the switch from this PR and try to get the package with fix ingested in our system as soon as we can.

**Comment by smitpatel** [comment]
Bit unrelated to this change (which only affects netcoreapp2.0), the fix which went in dev branch, I was running it on windows 7 machine. It is stuck while testing SqlServer functional tests on net46 (error similar to appveyor). Its been like that for 15h now. Probably msbuild or xunit hang. fyi: @mikeharder

**Comment by mikeharder** [comment]
Regarding the test hang, we would need to debug.  @smitpatel: If you can keep a live repro around I can investigate later today.

Let's test the latest package at https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Data.SqlClient.  If it has the fix, I will work with @kichalla to get this version mirrored to our feed.

**Comment by mikeharder** [comment]
I verified that https://github.com/dotnet/corefx/issues/18997 is fixed in `4.4.0-preview2-25227-02` at https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Data.SqlClient.  I will get this build mirrored to https://dotnet.myget.org/feed/aspnetcore-ci-dev/package/nuget/System.Data.SqlClient, then we should be able to remove the workarounds in EF tests, and all tests should pass.

**Comment by mikeharder** [comment]
I accidentally tested the preview2 build.  I will test with latest preview1 build instead.

**Comment by mikeharder** [comment]
This is also fixed in `System.Data.SqlClient 4.4.0-preview1-25227-04`.  This is the version we will mirror to our feed.

**Comment by mikeharder** [comment]
Packages have been mirrored to https://dotnet.myget.org/gallery/aspnetcore-ci-release, so this change can be checked into preview1 **without** the test workarounds.

**Comment by mikeharder** [comment]
Packages have also been mirrored to https://dotnet.myget.org/gallery/aspnetcore-ci-dev, which should unblock tests in the dev branch.  The EF test workarounds can be reverted in dev as well.

**Comment by smitpatel** [comment]
@mikeharder - Multiple questions:

I am not able to find packages on our feeds neither dev not release.
Will release feed have 4.4.0-preview1 & dev 4.4.0-preview2 respectively or do we have to specific suffix explicitly?

**Comment by smitpatel** [comment]
Updated PR after discussing with Mike.

**Comment by kichalla** [comment]
@smitpatel they should be with `preview1` (we have not yet started mirroring `preview2` and would like to keep it like that at least for this week)

**Comment by mikeharder** [comment]
@kichalla The packages are correctly mirrored, we resolved the confusion.

**Pull request merged**
