### PR TITLE
Add missing dependency to Relational tests

### PR DESCRIPTION
**Pull request by bricelam**
Still running tests locally...

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
:shipit:

**Comment by bricelam** [comment]
Hmm, now I'm getting
> error CS0246: The type or namespace name 'IServiceCollection' could not be found (are you missing a using directive or an assembly reference?)

**Comment by bricelam** [comment]
@anurse Is something currently broken in dependency resolution?

**Comment by anurse** [comment]
Not that I know of

**Comment by bricelam** [comment]
Merged as part of 98bcccd99eff9b85f17a8ac6782894d4b75dcc8d

**Pull request closed without merging**
