### PR TITLE
Update relinq2.0.0 alpha.4 (Resolves #2162)

### LINKED ISSUE #2162: Upgrade of re-linq to 2.0.0-alpha.4
Hi @ajcvickers!

Figured this is the most straight forward way to do this: I'll be getting ready with the next drop of re-linq in the next couple of days and am going to send you guys a PR with the breaking changes already fixed (baring unforseen troubles). There's going to be a longer post about them over on our mailing list but the gist is that re-linq now depends on System's ExpressionVisitor instead of our own implementation from way back when (.NET 3.5 times). I would propose to update the namespaces, derived visitors, etc accordingly (namespace "ExpressenTreeVisitors" -> "ExpressionVisitors", etc)

I also removed the ExtensionExpression since it's no longer needed in .NET 4. Unless you guys would like to keep a common base class for Expressions?

Best regards, Michael

### PR DESCRIPTION
**Pull request by MichaelKetting**
(Summary taken from the commit messages:)

* Updated API changes:
 * Replaced ExpressionTreeVisitor with RelinqExpressionVisitor for base types and System.Linq.ExpressionVisitor for parameters and return types.
 * Renamed ExpressionVisitor.VisitExpression() to Visit()
 * Renamed expression-type specific visit-methods from VisitAbcExression() to VisitAbc()
 * Changed Expression.Accept() method from public to protected.
 * Replaced calls to expression.Accept(visitor) with visitor.Visit(expression)
 * Replaced Remotion.Linq.ExtensionExpression with ExtensionExpression base type defined by EntityFramework (will be removed in separate commit)
 * Replaced FormattingExpressionVisitor.Format(expression) with expression.ToString().
* Renamed folders 'ExpressionTreeVisitors' to 'ExpressionVisitors'.
* Renamed types derived from ExpressionVisitor from 'AbcExpressionTreeVisitor' to 'AbcExpressionVisitors'.
* Replaced Remotion.Linq.ExtensionExpression with System.Linq.Expression.
 * Overridden NodeType-property to return ExpressionType.Extension.
 * Overridden Type-property to return the Type value.
* Introduced caching for NodeTypeProvider: 
Creating the NodeTypeProvider is a non-trivial operation but it can be cached. The CacheableNodeTypeProvider decorator hides the mutable members, preventing client code from accessing them via casting.

### CODE REVIEW

**Comment by rowanmiller** [comment]
Hey All,

Just a quick note to let you know that we will be merging contributions from folks outside the EF team here at Microsoft shortly. We just need to hold off for a little longer while we branch for our next release. There is some process around shipping external contributions with Visual Studio, so we need to branch for our next pre-release before taking any further contributions.

~Rowan

**Comment by anpete** [comment]
Hi @MichaelKetting, we're ready for this now. Can you rebase it to dev?

**Comment by maumar** [comment]
I would like to checkin one thing before. Will post here once the change is in.

**Comment by MichaelKetting** [comment]
@maumar I can see why :wink: I did do a rebase for integration purposes but leave the order up to the EF guys. 

@anpete It's rebased and but I couldn't do a complete re-test of the final rebase after you guys reintegrated the release branch. Something's weirdly broken now since neither the console nor VS is able to resolve all the dependencies. 

I've tried setting up a clean slate as far as I can tell by deleting all the bin and obj folders, the packages in the solution folder and .dnx folder. 

In Visual Studio, compiling mostly works except for a missing System.IO reference in Sqlite:
C:\Development\AspNetVNext\EntityFramework\src\EntityFramework.Sqlite\SqliteDataStoreCreator.cs(85,17,85,21): error CS0103: The name 'File' does not exist in the current context

In the console, I did a "dnvm upgrade -u", then "dnu restore", then "build.cmd". This results in 

Building EntityFramework.Commands for .NETCore,Version=v5.0
*snip*
  Using Package dependency Microsoft.Framework.Configuration.Abstractions 1.0.0-beta6-11408
    Source: C:\Users\michael.ketting\.dnx\packages\Microsoft.Framework.Configuration.Abstractions\1.0.0-beta6-11408
    File: lib\portable-net45+win\Microsoft.Framework.Configuration.Abstractions.dll
  Unable to resolve dependency framework/System.Threading.Tasks
  Unable to resolve dependency framework/System.Collections
  Unable to resolve dependency framework/System.Collections.Concurrent
  Unable to resolve dependency framework/System.Threading
  Unable to resolve dependency framework/System.Reflection
  Unable to resolve dependency framework/System.Runtime.Extensions
  Unable to resolve dependency framework/System.Linq
  Unable to resolve dependency framework/System.ComponentModel
  Unable to resolve dependency framework/System.Runtime
  Unable to resolve dependency framework/System.Diagnostics.Debug
  Unable to resolve dependency framework/System.Globalization
  Unable to resolve dependency framework/System.Linq.Expressions
  Unable to resolve dependency framework/System.Resources.ResourceManager
  Unable to resolve dependency framework/System.Runtime.InteropServices
C:\Development\AspNetVNext\EntityFramework\src\EntityFramework.Relational.Design\project.json(10,35): error: Dependency EntityFramework.Relational >= 7.0.0-* could not be resolved
C:\Development\AspNetVNext\EntityFramework\src\EntityFramework.Relational\project.json(8,29): error: Dependency EntityFramework.Core >= 7.0.0-* could not be resolved
C:\Development\AspNetVNext\EntityFramework\src\EntityFramework.Commands\project.json(0,0): error: Dependency framework/System.Threading.Tasks  could not be resolved
C:\Development\AspNetVNext\EntityFramework\src\EntityFramework.Commands\project.json(0,0): error: Dependency framework/System.Collections  could not be resolved
C:\Development\AspNetVNext\EntityFramework\src\EntityFramework.Commands\project.json(0,0): error: Dependency framework/System.Collections.Concurrent could not be resolved
C:\Development\AspNetVNext\EntityFramework\src\EntityFramework.Commands\project.json(0,0): error: Dependency framework/System.Threading  could not be resolved
C:\Development\AspNetVNext\EntityFramework\src\EntityFramework.Commands\project.json(0,0): error: Dependency framework/System.Reflection  could not be resolved
C:\Development\AspNetVNext\EntityFramework\src\EntityFramework.Commands\project.json(0,0): error: Dependency framework/System.Runtime.Extensions  could not be resolved
C:\Development\AspNetVNext\EntityFramework\src\EntityFramework.Commands\project.json(0,0): error: Dependency framework/System.Linq  could not be resolved
C:\Development\AspNetVNext\EntityFramework\src\EntityFramework.Commands\project.json(0,0): error: Dependency framework/System.ComponentModel  could not be resolved
C:\Development\AspNetVNext\EntityFramework\src\EntityFramework.Commands\project.json(0,0): error: Dependency framework/System.Runtime  could not be resolved
C:\Development\AspNetVNext\EntityFramework\src\EntityFramework.Commands\project.json(0,0): error: Dependency framework/System.Diagnostics.Debug  could not be resolved
C:\Development\AspNetVNext\EntityFramework\src\EntityFramework.Commands\project.json(0,0): error: Dependency framework/System.Globalization  could not be resolved
C:\Development\AspNetVNext\EntityFramework\src\EntityFramework.Commands\project.json(0,0): error: Dependency framework/System.Linq.Expressions  couldnot be resolved
C:\Development\AspNetVNext\EntityFramework\src\EntityFramework.Commands\project.json(0,0): error: Dependency framework/System.Resources.ResourceManager  could not be resolved
C:\Development\AspNetVNext\EntityFramework\src\EntityFramework.Commands\project.json(0,0): error: Dependency framework/System.Runtime.InteropServices could not be resolved
Build failed.

Do you have any suggestions what I'm missing here?

**Comment by maumar** [comment]
my changes are now in dev. The issues you are seeing are expected. There are some problems with the build at the moment. We are working on getting it back to the correct state. However I was able to to build in VS and run tests from there. Perhaps some things were already fixed since the time you tried it.

**Comment by MichaelKetting** [comment]
@maumar Hmm...your commit's the only one that's new since the previous update, so I'm not too hopeful about the System.IO error in Sqlite just going away. When I check the project's references, I see:
* Analyzers
* .NET 
* EntityFramework.Core 
* EntityFramework.Relational
* Microsoft.Data.Sqlite
* Microsoft.Framework.DependencyInjection
* Microsoft.Framework.DependencyInjection.Abstractions, Logging
* Microsoft.Framework.Logging
* Remotion.Linq
* System.Data.Common

Should I also have System.IO listed or is this supplied via the .NET reference.

Anyhow, I can still test without Sqlite. It's just a bit more tedious. Will be doing the rebase tomorrow (yay for 9 hours of time difference :smile: )

**Comment by maumar** [comment]
Ah, yes, that is a separate problem. For the purpose of verification for my change I commented out the affected line. But hopefully we will have the repo working by the time you get a change to rebase again! ;)

**Comment by MichaelKetting** [comment]
@anpete PR is up to date.

**Comment by anpete** [comment]
Merged, thanks @MichaelKetting!

**Pull request closed without merging**
