### PR TITLE
Basic cleanup of SQL Server provider namespaces

### PR DESCRIPTION
**Pull request by ajcvickers**

### CODE REVIEW

**Comment by ErikEJ** [comment]
@ajcvickers Is this something you suggest other providers to also do?

**Comment by ajcvickers** [comment]
@ErikEJ We are currently doing API review of the provider assemblies. This is the first part of that work, but there are also some other changes coming. It would be a good idea to keep your provider updated so that the APIs align, but it is obviously not strictly necessary.

**Comment by ErikEJ** [comment]
Thanks, I will attempt to align namespaces

**Comment by bricelam** [comment]
:shipit:

**Comment by rowanmiller** [comment]
@ErikEJ our general rule with providers etc. is that we don't introduce a provider specific sub-namespace. Types keep the same namespace as the type they inherit from core (or the related types in core). We do introduce some sub-namespaces when it makes sense (i.e. we introduce `Microsoft.Data.Entity.Migrations` in relational, because there is no migrations concept in core).

**Comment by rowanmiller** [comment]
cc @roji since you may want to apply these same rules in Npgsql

**Comment by roji** [comment]
Thanks @rowanmiller, have applied this in Npgsql

**Pull request merged**
