### PR TITLE
Several reverse engineering bug fixes

### PR DESCRIPTION
**Pull request by LunicLynx**

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@LunicLynx__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by LunicLynx** [comment]
Just realized, there is a Test that requires changes aswell.
The Annotation_check_arguments Test expects an ArgumentException when calling with an empty String.

**Comment by rowanmiller** [comment]
@LunicLynx  just following up to see if you are planning to sign an agreement so that we can process your pull request?

**Comment by LunicLynx** [comment]
I did, twice, but nothing happend...

Sent from my Windows Phone
________________________________

**Comment by rowanmiller** [comment]
@LunicLynx I'll look into it from our side.

**Comment by rowanmiller** [comment]
@LunicLynx looks like there was a technical issue on our end (your CLA was received)

@lajones you are good to look at this one now

**Comment by lajones** [comment]
Checked in with commit ef87f3d - see PR#1987. Thanks @LunicLynx for the contribution.

**Pull request closed without merging**
