### PR TITLE
Add passing SQLite tests

### PR DESCRIPTION
**Pull request by bricelam**
There were a lot failing that we still need to investigate:
- AsyncFromSqlQueryTest
- AsyncQueryTest
- BuiltInDataTypesTest
- FromSqlQueryTest
- GearsOfWarQueryTest
- GraphUpdatesTest
- IncludeOneToOneTest
- InheritanceTest
- MappingQueryTest
- MonsterFixupTest
- NullSemanticsQueryTest
- OptimisticConcurrencyTest
- QueryTest
- StoreGeneratedTest
- TransactionTest

### CODE REVIEW

**Comment by ajcvickers** [comment]
:shipit:

**Comment by ErikEJ** [comment]
@bricelam Is the general idea that any relational provider should pass all tests listed above and the ones in this PR?

**Comment by bricelam** [comment]
@ErikEJ In theory, all provider-agnostic tests should pass on every provider--assuming that the functionality tested is supported (e.g. sequences won't work on SQLite). But, as this PR illustrates, this is not currently the case. We need to update the tests and possibly the framework to remove some of the SQL Server-specific assumptions.

**Comment by ErikEJ** [comment]
@bricelam Thanks, Brice. I will see how far I can get with my little provider. At least I should not despair if I have too many failng functional tests :+1:

**Pull request merged**
