### PR TITLE
[SMALL, RevEng] Map SQLServer xml columns to string properties.

### PR DESCRIPTION
**Pull request by lajones**
Partial fix for #3076. Update RevEng SQL Server provider to map xml columns to string properties.

### CODE REVIEW

**Comment by natemcmaster** [comment]
Have we considered the [limitations of xml data type](https://msdn.microsoft.com/en-us/library/hh403385.aspx#Anchor_4)? This simple PR works from database => model. Does EF handle xml columns types the other way?

**Comment by lajones** [comment]
@natemcmaster Yes - I did some testing and EF handles insert, update and delete going the other way. You can get into problems if you try to store some (but not all) non-XML e.g. `">'<"` causes problems but just `"someText>"` does not. You get a `DbUpdateException` which explains (in the inner exception) that it had trouble parsing the string as XML. Discussed these limitations with @rowanmiller and decided they were OK.

**Comment by rowanmiller** [comment]
Yeah I've done some playing around with it for demos etc. and it works for the mainline cases just fine.

**Comment by natemcmaster** [comment]
Ok. Changes here look fine then. :shipit:

**Comment by lajones** [comment]
Checked in with commit a8b185f.

**Pull request closed without merging**
