### PR TITLE
Rename M.D.E.Relational.Design namespace to M.D.E.Scaffolding.

### LINKED ISSUE #2956: RevEng: minimize "public" API surface
We should move everything that is not consumed by providers to a .Internal namespace.

The main reason is that we need to design our template-based code gen feature (#2947) and this will have a large impact on the shape of the APIs.

### PR DESCRIPTION
**Pull request by natemcmaster**
Responding to API review changes.
Moving code gen to .Internal namespace

Close #2956.

Related TODO https://github.com/aspnet/EntityFramework/issues/3490

### CODE REVIEW

**Comment by natemcmaster** [comment]
cc @rowanmiller  and @lajones

**Comment by ErikEJ** [comment]
No file renames?

**Comment by lajones** [comment]
Looks good :shipit:

**Comment by natemcmaster** [comment]
@ErikEJ Only where class names changed. This is mostly a namespace update. The assembly names are also the same.

**Comment by ErikEJ** [comment]
Once this is in, will it be a good time to re-enable the sqlce design provider?

**Comment by natemcmaster** [comment]
@ErikEJ yes. We have been hard at working polishing the provider-api for reverse engineering. We'd love feedback on it.

**Comment by natemcmaster** [comment]
:watch: api review. Class renames to be included as well.

**Comment by ErikEJ** [comment]
@natemcmaster I wonder if it could be possible to call the code generation somehow from a VS xtension - that would be a natural next step for me, as I already have similar UI for  EF4 & EF6 ?

**Comment by natemcmaster** [comment]
@erikej Your UI would need to use similar startup logic found in the commands project to ensure services are configured correctly. And btw, most of the actually code gen code will move into Commands soon. See #3490

**Comment by rowanmiller** [comment]
@ErikEJ we are planning to build an extension and have a pre-release available on VS Gallery as close to RC1 as possible (hopefully at the same time it is released).

**Comment by natemcmaster** [comment]
Updated with class renames.

### Providers Beware...

To keep this PR smaller, the following will be added in a followup PR.

- [ ] Remove IMethodNameProvider and use annotation instead. Throw when missing.
- [ ] Make TableSelectionSet immutable
- [ ] Make EntityType errors annotations on model, rather than including empty entity types in the scaffolding model
- [ ] Discover/respsect IsClustered indexes on SqlServer
- [ ] Change ColumnModel to use EF's value generation heuristics rather than the current, ambiguously-named flags
- [ ] Possibly remove ExplicitValueGenerationNever annotation

**Comment by lajones** [comment]
:shipit:

**Pull request merged**
