### PR TITLE
Move scaffolding code generation into EntityFramework.Commands assembly

### LINKED ISSUE #3490: Scaffolding: move implementation of code gen into Commands project
Will require splicing some classes (CSharpUtilities and ModelUtilities) so we don't have circular dependencies.

### PR DESCRIPTION
**Pull request by natemcmaster**
Fix #3490.

 - Move E2E scaffolding testing into EF.Commands.FunctionalTests
 - Remove the now empty EF.Relation.Design.FunctionalTests assembly/project/package
 - Remove unused strings from RelationalDesignStrings
 - Split some internal classes to divide code-gen functionality

### CODE REVIEW

**Comment by natemcmaster** [comment]
cc @bricelam @lajones

**Comment by ErikEJ** [comment]
Pls remember to publish the new Commands.FunctionalTest package on Myget and NuGet feeds

**Comment by bricelam** [comment]
We can probably simplify the packages a bit more. I'll take a closer look on Monday.

**Comment by bricelam** [comment]
I don't like the idea of providers needing to use EF.Commands.FunctionalTests. It feels like we could refactor our provider-agnostic tests better to remove the dependency on EF.Commands.

**Comment by natemcmaster** [comment]
Our E2E tests right now don't follow a consistent pattern. It would be nice to help providers write better E2E tests, but we need to cleanup our test infrastructure ourselves. Ideally, we could have a general E2E testing on commands that we can re-use for migrations, reveng, update, etc.

**Comment by bricelam** [comment]
Product changes look good. We're one step closer to #2646 :wink:

**Comment by bricelam** [comment]
Discussed in-person: We don't want to "ship" EF.Commands.FunctionalTests. We'll re-introduce EF.Relational.Design.FunctionalTests and make it depend on EF.Commands.

**Comment by lajones** [comment]
As far as I'm concerned :shipit:. But maybe check with @bricelam as well.

**Comment by natemcmaster** [comment]
@bricelam  I updated to reverse changes you made in https://github.com/aspnet/EntityFramework/pull/3686. I just double checked and this does not regress on https://github.com/aspnet/EntityFramework/issues/3681.

**Comment by bricelam** [comment]
:shipit:

**Pull request merged**
