### PR TITLE
React to WebHostingBuilder

### PR DESCRIPTION
**Pull request by HaoK**
https://github.com/aspnet/Hosting/pull/237

cc @divega @davidfowl Any way to avoid CallContextServiceLocator here?

### CODE REVIEW

**Comment by bricelam** [comment]
I can flow in the `IServiceProvider` from the `Program` class. File a bug and I'll fix.

**Comment by bricelam** [comment]
:shipit: Can service building be decoupled from hosting? It feels like the `Startup.ConfigureServices` pattern of building services is orthogonal from the rest of the hosting pipeline.

**Comment by HaoK** [comment]
Great, filed https://github.com/aspnet/EntityFramework/issues/2024

**Comment by HaoK** [comment]
re splitting service building, I'm not sure we can, since Startup potentially can take things like IHostingEnvironment in its ctor which only come from hosting.

**Comment by HaoK** [comment]
99ebd0cf3f8755bb9a25e63aa464388f374eb71e

**Pull request closed without merging**
