### PR TITLE
[Tiny] Switch to MSBuild of VS 2015

### PR DESCRIPTION
**Pull request by smitpatel**
Builds correctly with VS 2015 (CTP edition) & Sql Server 2012 (SP2)

### CODE REVIEW

**Comment by smitpatel** [comment]
Should I also create issue to switch to Sql server 2014?

**Comment by divega** [comment]
> Should I also create issue to switch to Sql server 2014?

Yes, if we don't have one already.

**Comment by bricelam** [comment]
:shipit:

**Comment by julielerman** [comment]
Is it correct that the build.cmd no longer works with VS2013? The output where it fails says its targeting MSBuild\14.0 and I'm getting a file not found error. If that's the case, you should update the wiki (https://github.com/aspnet/EntityFramework/wiki/Getting-and-Building-the-Code).

**Comment by ErikEJ** [comment]
@julielerman why not do a PR? 😁

**Comment by julielerman** [comment]
Please see https://github.com/aspnet/EntityFramework/issues/1570

**Comment by bricelam** [comment]
It is intentional; we're using C# 6 features now. Yes, wikis always need updating. ;) That's why I avoid them.

**Pull request merged**
