### PR TITLE
Migrations: Scaffold Required for Primary Key Properies

### LINKED ISSUE #1978: Conventions: Make key properties required
Problem seems to be that upon rename we create nullable column which then can't be made a Primary key.

Configuration before:

```

    public class GearsOfWarContext : DbContext
    {
        public GearsOfWarContext()
        {
        }

        public DbSet<City> Cities { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(new SqlConnectionStringBuilder { DataSource = ".", InitialCatalog = "Beta4Bash_Migrations", MultipleActiveResultSets = true, IntegratedSecurity = true }.ToString());
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<City>().Key(e => e.Name).ForRelational().Name("Foobar");
            modelBuilder.Entity<City>().Property(e => e.LocationChange);
            modelBuilder.Entity<City>().Property(e => e.LocationChange).MaxLength(40);

            modelBuilder.Entity<City>().Property<DateTime>("Shadow");
        }
    }

    public class City
    {
        public string Name { get; set; }
        public int LocationChange { get; set; }
    }
```

Configuration after:

```

    public class GearsOfWarContext : DbContext
    {
        public GearsOfWarContext()
        {
        }

        public DbSet<City> Cities { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(new SqlConnectionStringBuilder { DataSource = ".", InitialCatalog = "Beta4Bash_Migrations", MultipleActiveResultSets = true, IntegratedSecurity = true }.ToString());
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<City>().Key(e => e.NameId).ForRelational().Name("Foobar");
            modelBuilder.Entity<City>().Property(e => e.LocationChange);
            modelBuilder.Entity<City>().Property(e => e.LocationChange).MaxLength(40);

            modelBuilder.Entity<City>().Property<DateTime>("Shadow");
        }
    }

    public class City
    {
        public string NameId { get; set; }
        public int LocationChange { get; set; }
    }
```

Migration:

```
        public override void Up(MigrationBuilder migration)
        {
            migration.DropPrimaryKey(name: "Foobar", table: "City");
            migration.DropColumn(name: "Name", table: "City");
            migration.AddColumn(
                name: "NameId",
                table: "City",
                type: "nvarchar(450)",
                nullable: true);
            migration.AddPrimaryKey(
                name: "Foobar",
                table: "City",
                column: "NameId");
        }
        
        public override void Down(MigrationBuilder migration)
        {
            migration.DropPrimaryKey(name: "Foobar", table: "City");
            migration.DropColumn(name: "NameId", table: "City");
            migration.AddColumn(
                name: "Name",
                table: "City",
                type: "nvarchar(450)",
                nullable: true);
            migration.AddPrimaryKey(
                name: "Foobar",
                table: "City",
                column: "Name");
        }
```

Exception:

System.Data.SqlClient.SqlException (0x80131904): Cannot define PRIMARY KEY constraint on nullable column in table 'City'.
At line:1 char:1
+ dnx . ef migration apply
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.Data.Sql...n table 'City'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Could not create constraint. See previous errors.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean 
breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.Data.Entity.Relational.SqlStatementExecutor.<>c__DisplayClass7_0.<ExecuteNonQuery>b__0()
   at Microsoft.Data.Entity.Relational.SqlStatementExecutor.Execute(IRelationalConnection connection, Func`1 action)
   at Microsoft.Data.Entity.Relational.SqlStatementExecutor.ExecuteNonQuery(IRelationalConnection connection, DbTransaction transaction, IEnumerable`1 sqlBatches)
   at Microsoft.Data.Entity.Relational.Migrations.Migrator.Execute(IEnumerable`1 sqlBatches, Boolean ensureDatabase)
   at Microsoft.Data.Entity.Relational.Migrations.Migrator.ApplyMigrations(String targetMigration)
   at Microsoft.Data.Entity.Commands.MigrationTool.ApplyMigration(String migrationName, String contextTypeName)
   at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass10_0.<ApplyMigration>b__0()
   at Microsoft.Data.Entity.Commands.Program.ExecuteInDirectory(String startupProject, Func`1 invoke)
   at Microsoft.Data.Entity.Commands.Program.ApplyMigration(String migration, String context, String startupProject)
   at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass7_2.<Main>b__8()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Data.Entity.Commands.Program.Main(String[] args)
ClientConnectionId:73c919fd-63dc-4c08-8b6d-ed1f32af40dc

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #1978

### CODE REVIEW

**Comment by ajcvickers** [comment]
@smitpatel A property that is a primary key will always report as non-nullable due to your previous change. This means scaffolding Required should have no impact on the model. Why then do we now need to scaffold Required for primary key properties? What am I missing?

**Comment by smitpatel** [comment]
@ajcvickers - Even though complete model gives correct value for nullability, migration still scaffolds the properties as nullable even though primary key. Therefore the issue mentioned in #1978 is still reproduces. Should we fix this in some other way? @bricelam - thoughts?

**Comment by ajcvickers** [comment]
@smitpatel I thought the change you made would make it impossible for a primary key property to be nullable in the model. If that is not the case, then maybe we should re-visit that code.

**Comment by smitpatel** [comment]
@ajcvickers - That code is correct. I tried to repro that bug in sample project and it was still there though it is working now. I guess I had some wrong packages installed while testing. Closing this as bug is fixed already.

**Pull request closed without merging**
