### PR TITLE
CLI Commands: Fix design-time assembly resolution

### LINKED ISSUE #3862: System.TypeLoadException on applying migrations on sqlite [OSX]
Steps to reproduce
1. Create a fresh Web application using 'aspnet' yo generator
2. Restore and build using rc1 release of mono
3. Apply migrations for the IdentitySchema 

```
mlxxxx% dnx ef database update
System.TypeLoadException: Could not load type 'Microsoft.Data.Entity.Scaffolding.SqliteDesignTimeServices, EntityFramework.Sqlite.Design' from assembly ''.
  at Microsoft.Data.Entity.Design.Internal.DesignTimeServicesBuilder.ConfigureProviderServices (System.String provider, IServiceCollection services, Boolean throwOnError) <0x5f98d60 + 0x00023> in <filename unknown>:0
  at Microsoft.Data.Entity.Design.Internal.DesignTimeServicesBuilder.Build (Microsoft.Data.Entity.DbContext context) <0x5d72af0 + 0x00133> in <filename unknown>:0
  at Microsoft.Data.Entity.Design.MigrationsOperations.UpdateDatabase (System.String targetMigration, System.String contextType) <0x5b4a158 + 0x00039> in <filename unknown>:0
  at Microsoft.Data.Entity.Commands.Program+Executor+<>c__DisplayClass7_0.<UpdateDatabase>b__0 () <0x35c8dc8 + 0x00034> in <filename unknown>:0
  at Microsoft.Data.Entity.Commands.Program+Executor.Execute (System.Action action) <0x35c8d48 + 0x0001c> in <filename unknown>:0
Could not load type 'Microsoft.Data.Entity.Scaffolding.SqliteDesignTimeServices, EntityFramework.Sqlite.Design' from assembly ''.

Version information

mlxxxx% yo --version
1.5.0

mlxxxx% dnvm list
Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
       1.0.0-rc1-final      coreclr x64          darwin
  *    1.0.0-rc1-final      mono                 linux/osx       default

mlxxxx% dnu --version
Microsoft .NET Development Utility
 Version:      1.0.0-rc1-16202
 Type:         Mono
 Architecture: x64
 OS Name:      Darwin
 OS Version:   10.10
 Runtime Id:   osx.10.10-x64

mlxxxx% dnvm --version
1.0.0-rc2-15545

mlxxxx% dnx --version
Microsoft .NET Execution environment
 Version:      1.0.0-rc1-16202
 Type:         Mono
 Architecture: x64
 OS Name:      Darwin
 OS Version:   10.10
 Runtime Id:   osx.10.10-x64
```
Note: Switching to Coreclr-rc1-final solves the issue though.

### LINKED ISSUE #3925: Commands: .NET Core CLI Implementation
DNX commands will be going away with the transition to [.NET Core CLI](https://github.com/dotnet/cli). We'll need to create a .NET Core CLI tools package instead. Like the NuGet PMC commands, any version of the command should be able to work with any version of the framework.

Known Issues
------------

- [x] System.DllNotFoundException: Unable to load DLL 'sni.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) (#4953)
- [x] Unable to load DLL 'sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E) (dotnet/cli#2289)
- [x] Could not load file or assembly 'System.Data.SqlClient, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. (dotnet/cli#2289)
- [x] Support netcoreapp1.0 apps
- [x] Hosting environment not setup correctly. https://github.com/aspnet/EntityFramework/issues/5065
- [x] Newtonsoft.Json 7.0.0 missing at runtime https://github.com/NuGet/Home/issues/2462
- [x] Newtonsoft.Json 8.0.0 could not be loaded at runtime https://github.com/dotnet/cli/issues/2514. Workaround in #5082 
- [x] ~~Tools using ConfigurationBuilder without setting basepath cannot find config files.~~ won't fix. User's need to set base path to IApplicationEnvironment.ApplicationBasePath.
- [x] Need to change to nested-dispatch model because `AssemblyLoadContext` does not provide the necessary isolation https://github.com/dotnet/cli/issues/2514
- [x] Cannot use dotnet-ef on a netstandard library or standalone app with nested-dispatch https://github.com/dotnet/cli/issues/2645

Usage
-----
Your `project.json` should look something like this.

```JSON
{
    "compilationOptions": {
        "emitEntryPoint": true
    },
    "tools": {
        "Microsoft.EntityFrameworkCore.Tools": { 
            "version": "1.0.0-*",
            "imports": "portable-net452+win81"
         }
    },
    "dependencies": {
        "Microsoft.EntityFrameworkCore.Sqlite": "1.0.0-*",
        "Microsoft.EntityFrameworkCore.Sqlite.Design": { "version": "1.0.0-*", "type": "build" },

        "Microsoft.EntityFrameworkCore.Tools": { "version": "1.0.0-*", "type": "build" }
    },
    "frameworks": {
        "netcoreapp1.0": {
            "imports": "portable-net452+win81",
            "dependencies": {
                "Microsoft.NETCore.App": { 
                     "version": "1.0.0-*",
                     "type": "platform"
                 }
            }
        }
    }
}
```

Your workflow will look something like this.

    dotnet restore
    cd src\MyProject
    dotnet ef migrations add MyMigration
    dotnet ef database update

### PR DESCRIPTION
**Pull request by bricelam**
Resolves #3925

**Provider writers beware**, this splits `DesignTimeProviderServicesAttribute.FullyQualifiedTypeName` into `TypeName` and `AssemblyName`. (cc @rowanmiller)

This should also fix #3862

### CODE REVIEW

**Comment by lajones** [comment]
:shipit: But maybe talk to @ajcvickers first - he raised #3111 which was to do the opposite and combine `TypeName` and `AssemblyName`.

**Comment by bricelam** [comment]
The choices were...
* Undo #3111
* Parse `FullyQualifiedTypeName`

I went with the simplest option. :wink: I'll bring it up in triage.

**Comment by ErikEJ** [comment]
@bricelam Does this mean I should strong sign the SQL CE provider?

**Comment by bricelam** [comment]
@ErikEJ No, it should still be optional.

**Pull request merged**
