### PR TITLE
Wait for localdb database files to be deleted instead of deleting them

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Part of #3902

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
First stab at the issue. @natemcmaster @bricelam

**Comment by natemcmaster** [comment]
Why do we need to wait? Can't we safely assume that if the "DROP DATABASE" command executes that SQL Server will cleanup files appropriately?

**Comment by smitpatel** [comment]
`DROP DATABASE` command cleans up files appropriately but we can run into a case where the command is issued but we tried to use the same name before it gets deleted by file system.

**Comment by AndriySvyryd** [comment]
This is needed if the last ran didn't delete the database and we are trying to create it with the same name.

**Comment by natemcmaster** [comment]
It sounds like this is trying to compensate for weak collision detection in the "CreateTransient" logic.

**Comment by AndriySvyryd** [comment]
and to cleanup state from previous runs

**Comment by natemcmaster** [comment]
I would favor a solution that instead makes `SqlServerTestStore.CreateTransient` impervious to bad. [SqliteTestStore does this](https://github.com/aspnet/EntityFramework/blob/18439602ee448c15b0dfdafa23d455a856204a08/test/EntityFramework.Sqlite.FunctionalTests/SqliteTestStore.cs#L27) in the CreateTransient logic because cleanup is not guaranteed to execute. Caveat: this led to #3749, but this seems to be due to an issue in Dispose not being called correctly by xunit.

**Comment by AndriySvyryd** [comment]
There are other reasons that could make Dispose not run and leave the DB around. Without the cleanup logic we would need to drop them manually by connecting to the CI agents. Sqllite dbs are much easier to cleanup.

**Comment by AndriySvyryd** [comment]
Anyway the AppVeyor builds failed with the new timeout message, so I'll try Nate's suggestion

**Comment by natemcmaster** [comment]
Yeah, this is related to a second problem. This cleanup assumes localdb, which we do not always use. AppVeyor uses SQL Server 2014.

**Comment by AndriySvyryd** [comment]
I don't think it does, we wouldn't get this error:
```
System.Exception : Timeout when waiting for 'C:\Users\appveyor\Microsoft.Data.SqlServer.Scratch_1.mdf' to be deleted.
```

**Comment by AndriySvyryd** [comment]
AppVeyor passes now

**Comment by natemcmaster** [comment]
:shipit:

**Pull request merged**
