### PR TITLE
Upgrade re-linq to 2.1.1

### PR DESCRIPTION
**Pull request by natemcmaster**
cc @pranavkm @Eilon 

Parital fix for #5766

### CODE REVIEW

**Comment by divega** [comment]
:shipit:

**Comment by pranavkm** [comment]
Is this a custom build (that's not available on nuget.org)?

**Comment by natemcmaster** [comment]
It's unlisted.

**Comment by pranavkm** [comment]
Nice. :shipit:

**Comment by natemcmaster** [comment]
Thanks to @MichaelKetting for his help on this!

**Pull request merged**
