### PR TITLE
Rename DatabaseProvider`.cs to DatabaseProvider.cs

### PR DESCRIPTION
**Pull request by fadihania**

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
@fadihania Do you experience any issues with the current name?

**Comment by anpete** [comment]
There is no non-generic version, which is why we normally would have "`" in the name. Not sure if we are fully consistent on this though.

**Comment by ajcvickers** [comment]
@anpete @AndriySvyryd We are not consistent. Often, as is the case here, there used to be a non-generic version. Personally I don't see much value in doing the rename, but I don't feel strongly one way or the other.

**Comment by anpete** [comment]
My vote would be to take it. I'm happy to merge it if others are OK with it.

**Comment by AndriySvyryd** [comment]
I'm ok with it

**Comment by ajcvickers** [comment]
I'm okay either way.

**Comment by fadihania** [comment]
@AndriySvyryd No, but I don't remember that I've seen this way of naming files used anywhere else in .NET repos. So, I thought it was a mistake

**Pull request merged**
