### PR TITLE
Use chaining for AddXxx methods now it is supported again.

### PR DESCRIPTION
**Pull request by ajcvickers**
AddLogging and AddMemoryCache now support chaining again.

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
:shipit:

**Comment by ErikEJ** [comment]
Providers beware?

**Comment by ajcvickers** [comment]
@ErikEJ I don't think so, unless I'm missing something.

**Comment by ErikEJ** [comment]
I was thinking about changes to: src/Microsoft.EntityFrameworkCore.SqlServer.Design/SqlServerDesignTimeServices.cs  !?

**Comment by ajcvickers** [comment]
@ErikEJ I don't think it has to return the IServiceCollection but to be consistent you could make the SQL CE one follow the same pattern.

**Comment by ErikEJ** [comment]
Will do, thanks!

**Pull request merged**
