### PR TITLE
Need a discuss and review, couple fixes and changes

### PR DESCRIPTION
**Pull request by multiarc**
#3235 fix - more than a fix, actually we could allow to use types as base types without strict declaration of base on model for example if we want separated tables with the same base entity and  ignore keys/properties from base type in child.

#3317 fix - select statement in SQL couldn't result in a bool, so just check the expression if it's select on binary expression and add " = 1"
Also MSSQL tests does have some missed parts on SQL generation if we have different FK/PK names and result SQL query was contain wrong table reference values because of small mistake. That was fixed in this commit.

### CODE REVIEW

**Comment by rowanmiller** [comment]
@anpete can you take a general look at these changes.

**Comment by anpete** [comment]
Assigning to @maumar as he has already looked at both of these issues.

**Comment by multiarc** [comment]
Regarding EntityQueryModelVisitor: 
I was trying to add type reference from expression if nothing found in model. This was added to allow correct navigation reference resolving when base type wasn't registered as entity and no relations was registered in model for base class.

```CSharp
public abstract class OptionValue
{
        public int Id { get; set; }
        public string Value { get; set; }
}

public abstract class DynamicData<TOptionValue>
        where TOptionValue: OptionValue
{
        public int Id { get; set; }
        public ICollection<TOptionValue> OptionValues { get; set; }
}

public class OrderOptionValue: OptionValue
{
        //...
}

public class Order: DynamicData<OrderOptionValue>
{
        //...
}
```

So when you try to resolve OptionValues collection in Order it will try to resolve OptionValue base abstract Type, but technically it should get OrderOptionValue with correct reference to right table.

The main point of all this is we can't change/ignore relations easily using Base declaration. 
We could have any kind of abstraction for base entity and don't mind how this declared or pointed to model so we declare just concrete classes and never think about base.

**Comment by anpete** [comment]
@multiarc Our main priority right now is to fix bugs and so that was the focus of this change. Feel free to open a new issue if you have ideas for how we can improve mapping around inheritance and nav. props.

**Comment by divega** [comment]
@anpete  :+1: 

@multiarc Thanks for your contribution. If I understand the scenario you described above correctly I agree it would be useful to make it work, so if it still not working a new issue (so that we can triage it and prioritize it) and a new PR would help.

**Pull request closed without merging**
