### PR TITLE
Add badges and links to packages to README.md

### LINKED ISSUE #5873: Add Badge / Link to Entity Framework Core SQL Server to Main GitHub README
Finding the NuGet Package requires some digging through the documentation.

https://docs.efproject.net/en/latest/ 
to https://docs.efproject.net/en/latest/providers/index.html 
to https://docs.efproject.net/en/latest/providers/sql-server/index.html 
to https://docs.efproject.net/en/latest/platforms/full-dotnet/index.html 
to https://docs.efproject.net/en/latest/platforms/full-dotnet/existing-db.html 
then scroll down until you find the `Install-Package Microsoft.EntityFrameworkCore.SqlServer`

Can we have direct link to https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer in the main README? Perhaps using something like http://shields.io/ to display links to common Entity Framework database providers / toolings packages badges that hyperlinks to the web page.

### PR DESCRIPTION
**Pull request by natemcmaster**
Close #5873 

Preview: https://github.com/natemcmaster/EntityFramework/blob/readme-patch-1/README.md

cc @rowanmiller

### CODE REVIEW

**Comment by smitpatel** [comment]
Appveyor & Travis build passing links should have labels.

**Comment by ryanelian** [comment]
That was fast.

Also probably because you guys just outed 1.0.0, the sentence `EF Core is currently pre-release.` under Roadmap section should be changed, no?

**Comment by natemcmaster** [comment]
Good point. I'll update that too.

**Comment by rowanmiller** [comment]
The search for `Microsoft.EntityFrameworkCore.*` on NuGet doesn't really give helpful results. Could we do links to some of the provider packages instead?

**Comment by natemcmaster** [comment]
:up::date:

**Comment by natemcmaster** [comment]
@smitpatel the labels for travis and appveyor appear in the image itself now.

**Pull request merged**
