### PR TITLE
[WIP] Upgrade Moq version

### PR DESCRIPTION
**Pull request by smitpatel**

### CODE REVIEW

**Comment by ajcvickers** [comment]
@smitpatel Don't forget to do the open-source dance with @Eilon 🕺 🕺

**Comment by smitpatel** [comment]
@ajcvickers - Thanks for reminder. This is still not fixing build. Seems like some breaking change in dotnet SDK/CLI

**Comment by Eilon** [comment]
Moq 4.7.8 is approved.

**Comment by smitpatel** [comment]
New version doesn't work.

**Pull request closed without merging**
