### PR TITLE
The smallest PR ever

### LINKED ISSUE #2855: Resolve System.Collections.Immutable version conflicts on CLR
Reverse engineering no longer works on CLR due to [recent changes in DNX](https://github.com/aspnet/dnx/pull/2474).

Reveng uses a version of Roslyn which is complied against System.Collections.Immutable 1.1.36.

EF.Core pulls in System.Collections.Immutable 1.1.37.

 On CLR, we resolved this with binding redirects https://github.com/aspnet/EntityFramework/commit/09412a130e0ff92d802dcc20fe0362f11be91f25 which worked until https://github.com/aspnet/dnx/pull/2474

@davidfowl @anurse @bricelam

### PR DESCRIPTION
**Pull request by natemcmaster**
Fix #2855

### CODE REVIEW

**Comment by natemcmaster** [comment]
Can we add this to the release branch? If we don't, scaffolding from the Package Manager Console will not work for the next beta.

**Comment by divega** [comment]
:shipit:

**Comment by divega** [comment]
Talked to @bricelam and he agreed that this is fine to unblock things in beta7 but he thinks we should probably be doing something else moving forward. @natemcmaster please talk to him and figure out how to capture that in a bug :smile:

**Comment by natemcmaster** [comment]
After discussion with @bricelam, we are going to wait to merge this until we have a final build for beta7. This original issue may be resolved with a new coherent set of packages.

**Comment by divega** [comment]
Hope you don't really mean final build (that would be too late :smile:), but sounds good.

**Comment by natemcmaster** [comment]
Just tested against the first coherent build. Still having version conflicts, so I will merge this to release.

**Pull request merged**
