### PR TITLE
Improvements for DefaultValue support

### LINKED ISSUE #4286: Configuring default value with fluent API doesn't support enum value without explicitly casting to int
Suppose we have model class with property of enum type that should be mapped to INT column in database. The class looks as follows

```csharp
public class Employee
{
    public int Id { get; set; }

    public OccupationType OccupationType { get; set; }
}

public enum OccupationType 
{
    Fulltime,
    Parttime,
    Freelance
}
```

Also we want to configure default value for that column with fluent API as follows:

```csharp
builder.Entity<Employee>()
    .Property(e => e.OccupationType)
    .HasDefaultValue(OccupationType.Fulltime);
```

Everything looks fine. Let's generate migration:
``` 
dnx ef migrations add AddEmployees
```

Here's what we get:
```
System.NotSupportedException: Annotations of type 'OccupationType' are not supported. Only common simple .NET types are currently supported.
   at Microsoft.Data.Entity.Infrastructure.TypedAnnotation.CheckType(Type type)
   at Microsoft.Data.Entity.Infrastructure.TypedAnnotation..ctor(Object value)
   at Microsoft.Data.Entity.Metadata.RelationalPropertyAnnotations.SetDefaultValue(Object value)
   at Microsoft.Data.Entity.Metadata.RelationalPropertyAnnotations.set_DefaultValue(Object value)
   at Microsoft.Data.Entity.RelationalPropertyBuilderExtensions.HasDefaultValue(PropertyBuilder propertyBuilder, Object value)
   at Microsoft.Data.Entity.RelationalPropertyBuilderExtensions.HasDefaultValue[TProperty](PropertyBuilder`1 propertyBuilder, Object value)
   at SomeProject.Models.ApplicationDbContext.OnModelCreating(ModelBuilder builder) in C:\Users\Alexander\Work\Github\EvAlex\SomeProject\src\SomeProject.Website\Models\ApplicationDbContext.cs:line 24
   at Microsoft.Data.Entity.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.Data.Entity.Infrastructure.ModelSource.<>c__DisplayClass8_0.<GetModel>b__0(Type k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Data.Entity.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.Data.Entity.Internal.DbContextServices.CreateModel()
   at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_5(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Data.Entity.Design.Internal.DesignTimeServicesBuilder.<>c__DisplayClass7_0.<ConfigureContextServices>b__8(IServiceProvider _)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Data.Entity.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.Data.Entity.Commands.Program.Executor.<>c__DisplayClass6_0.<AddMigration>b__0()
   at Microsoft.Data.Entity.Commands.Program.Executor.Execute(Action action)
```

It turns out that the problem is default value type. The error is in default value configuration and the correct syntax is:
```csharp
builder.Entity<Employee>()
    .Property(e => e.OccupationType)
    .HasDefaultValue((int)OccupationType.Fulltime);
//                   ^^^^^ here's the difference
```

The exception message is absolutely not clear.

### PR DESCRIPTION
**Pull request by smitpatel**
resolves #4286 
- Remove TypedAnnotation
- Validate the default value type with property type
- Store default value directly as annotation. Migration serializes it

### CODE REVIEW

**Comment by bricelam** [comment]
Are there existing tests for `enum` properties? (Especially for `CSharpSnapshotGenerator`)

**Comment by smitpatel** [comment]
No. DefaultValue is stored as annotation. IdentityStrategy is also stored as annotation and works fine in snapshot so I did not add extra test for DefaultValue specifically.

**Comment by bricelam** [comment]
But for default value, the enum is part of the user's model, and therefore needs to be unwrapped to the underlying type (like we do for the `.Property<T>()` call).

**Comment by bricelam** [comment]
:shipit: We'll fix the snapshot issue with #4061

**Pull request merged**
