### PR TITLE
Test: Update to AssertSql

### PR DESCRIPTION
**Pull request by smitpatel**
Takes params of string
Actual Sql is added as arg by the function
If only 1 string passed then exact match with actual Sql else contains match

@maumar @anpete

### CODE REVIEW

**Comment by ErikEJ** [comment]
@smitpatel Any easy way to get rid of the two leading spaces in the VS output window?

**Comment by smitpatel** [comment]
@ErikEJ - @anpete's trick, hold down `Alt` while selecting the output, it will do a box selection,

**Comment by ErikEJ** [comment]
@smitpatel Thanks, that is what I am doing currently! 😄

**Comment by smitpatel** [comment]
@ErikEJ - To avoid the issue of selecting the text, I updated to write new baselines to a file `QueryBaseline.cs` in repo root. I have tried to make it good enough so that it can work for provider writers too. Let me know if there are any issues for you.

**Comment by ErikEJ** [comment]
@smitpatel Great! Thanks, I will give it a try soon

**Comment by ErikEJ** [comment]
@smitpatel Thanks a lot for QueryBaseline.cs !

**Pull request merged**
