### PR TITLE
[TINY] Fix to #4549 - ExpressionEqualityComparer NullReferenceException

### PR DESCRIPTION
**Pull request by maumar**

### CODE REVIEW

**Comment by maumar** [comment]
@anpete

**Comment by divega** [comment]
Is the indentation actually wrong or is it just the diff? Why didn't this fail in any of our tests? Should we add one?

Otherwise :shipit:

**Comment by anpete** [comment]
:shipit:

**Comment by maumar** [comment]
Fixed the indentation. We don't have the test for, but I don't think we really need one. This only repros if you manually create ParameterExpression using the Expression builder API. I will take a look at other expressions though to see if there are more NREs like this.

**Pull request merged**
