### PR TITLE
Fixes #5333 - More generic solution for severity level of warnings

### LINKED ISSUE #5333: More generic solution for severity level of warnings (throw/warn/ignore)
Currently we have a special API for what happens with client eval during queries. We want to make this a more generic concept so that we can handle other warning types (such as ignored includes https://github.com/aspnet/EntityFramework/issues/5332). 

The min-bar for RTM is to have a context wide API. It would be nice to have the ability to override these on a per-query basis, so that you can say "I'm ok with client eval for this query" etc. But that can be split off to a separate issue if we don't get to it for RTM.

### PR DESCRIPTION
**Pull request by anpete**
- Adds ```DbContextOptionsBuilder.ConfigureWarnings(Action<WarningsConfigurationBuilder>)``` fluent API. The API has two main functions:
  1. Allow a default warning behavior to be set: ```builder.DefaultBehavior(WarningBehavior)``` default is 'Log'
  2. Configure explicit behavior for specific event ids. Throw, Log or Ignore. E.g. ```builder.Throw(CoreLoggingEventId.IncludeIgnoredWarning)```
- Re-uses our logging event ids as the way to identify specific warning kinds.
- Adds relational fluent extension methods on builder for relational event ids.
- Warning exception generation logic centralized in InterceptingLogger via LogWarning EF extensions.
- Replaces previous ad-hoc warnings: query client eval and ambient transaction detected.

### CODE REVIEW

**Comment by anpete** [comment]
@rowanmiller @divega New version of this

**Comment by rowanmiller** [comment]
API looks good to me. When we write errors, do we give the name (not value) of the corresponding EventId? I.e. is it easy for a dev to work out they need to use `CoreLoggingEventId.IncludeIgnored`?

**Comment by divega** [comment]
Maybe we could rename `DefaultBehavior()` to `Default()`, e.g.:

``` C#
.ConfigureWarnings(warnings => warnings
   .Default(WarningBehavior.Throw)
   .Ignore(CoreLoggingEventId.IncludeIgnoredWarning));
```

Instead of 

``` C#
.ConfigureWarnings(warnings => warnings
   .DefaultBehavior(WarningBehavior.Throw)
   .Ignore(CoreLoggingEventId.IncludeIgnoredWarning));
```

But maybe not :smile: What do you think?

Maybe the two things we already had become slightly less discoverable, but I think this is nice! :clap::clap::clap:

**Comment by rowanmiller** [comment]
@divega `Default(...)` looks good to me 👍

**Comment by anpete** [comment]
@rowanmiller @divega Will change to Default - looks good to me. And, @rowanmiller, this is what errors look like:

```
Warning as error exception for warning 'IncludeIgnoredWarning': The Include operation for navigation: 'e.Nav' was ignored because the target navigation is not reachable in the final query results.
```

**Comment by rowanmiller** [comment]
@anpete is there any way to easily get the fully qualified EventId enum name/value in there? Also, do we write the EventId name when we log the warning?

**Comment by anpete** [comment]
@rowanmiller I think that should be do-able. The first PR did it - it was easier because the APIs were different. WRT the event id and logging, no. Are you thinking about how people go from seeing the warning in logging to making a corresponding change in ConfigureWarnings?

**Comment by rowanmiller** [comment]
> Are you thinking about how people go from seeing the warning in logging to making a corresponding change in ConfigureWarnings?

Yes. In particular if they want to suppress the warning.

**Comment by anpete** [comment]
@divega @rowanmiller Another thing we should consider: Generalize our event ids be renaming to remove "Logging". I.e. CoreLoggingEventId -> CoreEventId

**Comment by rowanmiller** [comment]
@anpete 👍 to the rename. If we don't get the fully qualified name in to this change (which is fine) lets just make sure we have an issue tracking it.

**Comment by anpete** [comment]
@rowanmiller Fully qualified done. Proposal for logged warnings:

"The LINQ expression '[c].IsLondon' could not be translated and will be evaluated locally. This warning can be configured using DbContextOptionsBuilder.ConfigureWarnings with event id 'RelationalLoggingEventId.QueryClientEvaluationWarning'."

**Comment by rowanmiller** [comment]
Message looks good to me

**Comment by rowanmiller** [comment]
Super happy we are getting this into RTM 😄

**Comment by divega** [comment]
@ajcvickers to do final CR.

**Comment by ajcvickers** [comment]
:shipit:

**Comment by divega** [comment]
A few more things came to mind:
- It seems we used to throw by default on ambient transactions? Will this change it to a log by default? If yes,  I think it is OK, if no, it is inconsistent
- Should we treat in-memory's IgnoreTransaction() in a similar way? 
- Are we tying our hands when we say this API is about warnings? What if in the future we find an event that is bad enough we want it to throw by default, but we want to be able to configure it to log or be ignored? Would that also be considered a warning?

**Pull request merged**
