### PR TITLE
InMemory: Rewrite equality for byte[]

### PR DESCRIPTION
**Pull request by tuespetre**
Addresses #5806

### CODE REVIEW

**Comment by anpete** [comment]
Hi @tuespetre, thanks for the PR!

I wonder whether we should do this rewrite across the board. In particular, on relational when we end up not translating the comparison to the server (client-eval), we would still get a reference comparison. One idea I had was that we could rewrite binary equality comparisons to SequenceEqual at the QueryModel level. Then we would just need to teach the relational translator how to turn it back into SQL equality for byte arrays. What do you think?

**Comment by divega** [comment]
Related discussion #5936 cc @anpete.

**Comment by tuespetre** [comment]
@anpete that sounds good, especially coming back to this PR after working heavily with Relational the past month.

Plus I see I missed an `Expression.Not` in there 😱

**Comment by tuespetre** [comment]
@anpete so we do this rewrite across the board, and then on relational, a method call translator could be used to handle translating it back to SQL equality. Sound about right?

**Comment by tuespetre** [comment]
I'm going to back off of this one for now.

**Pull request closed without merging**
